### ISSUE TITLE
[v2 BUG]: dictionary update sequence element #0 has length 1; 2 is required

### ISSUE THREAD

**Issue by AquifersBSIM** [chemprop/chemprop#1104]
**Describe the bug**
As simple as the title, however, I dont know if this is the right place to write an issue to because this issue is more related to torch right. But, after switching from Chemprop v2.0.1 to v2.1.0, only then, this issue appeared. Not only that, but this issue only arises when I am doing ```logger=logger``` and/or ```logger=True```.

**Example(s)**
Here is the .csv file:
[vinardo_COX2_A_smiles.csv](https://github.com/user-attachments/files/17788861/vinardo_COX2_A_smiles.csv)

I will share the best minimal code that I can produce:
```python
from pathlib import Path
from lightning import pytorch as pl
from lightning.pytorch.callbacks import ModelCheckpoint
from chemprop import data, featurizers, models, nn
from lightning.pytorch.loggers import TensorBoardLogger
import numpy as np
import pandas as pd

input_path = "vinardo_COX2_A_smiles.csv" # path to your data .csv file
smiles_column = 'smiles' # name of the column containing SMILES strings
target_columns = ['docking scores'] # list of names of the columns containing targets
good_descriptors_based_on_SHAP_lit_column = ['NumRotatableBonds','TPSA', 'FractionCSP3','NumHBAcceptors',
                                          'NumRings', 'Hall-KierAlpha', 'MolarRefractivity', 'ExactMolWeight','LogP',
                                          'NumNitrogen', 'NumHBDonors', 'NumSulphurs', 'NumOxygen', 'TotalAromaticRings'
]

df_input = pd.read_csv(input_path)
df_input

smis = df_input.loc[:, smiles_column].values
ys = df_input.loc[:, target_columns].values
x_ds = df_input.loc[:, good_descriptors_based_on_SHAP_lit_column].values

print(smis)
print(ys)

all_data = [data.MoleculeDatapoint.from_smi(smi, y) for smi, y in zip(smis, ys)]

num_workers = 1
mols = [d.mol for d in all_data]  # RDkit Mol objects are use for structure based splits
train_indices, val_indices, test_indices = data.make_split_indices(mols)

print("LENGTH")
print(len(train_indices), len(val_indices), len(test_indices))

train_data, val_data, test_data = data.split_data_by_indices(
    all_data, train_indices, val_indices, test_indices
)

featurizer = featurizers.SimpleMoleculeMolGraphFeaturizer()

train_dset = data.MoleculeDataset(train_data[0], featurizer)
scaler = train_dset.normalize_targets()

val_dset = data.MoleculeDataset(val_data[0], featurizer)
val_dset.normalize_targets(scaler)

test_dset = data.MoleculeDataset(test_data[0], featurizer)

train_loader = data.build_dataloader(train_dset, num_workers=num_workers)
val_loader = data.build_dataloader(val_dset, num_workers=num_workers, shuffle=False)
test_loader = data.build_dataloader(test_dset, num_workers=num_workers, shuffle=False)

mp = nn.BondMessagePassing()
agg = nn.MeanAggregation()

output_transform = nn.UnscaleTransform.from_standard_scaler(scaler)
ffn = nn.RegressionFFN(output_transform=output_transform, input_dim=300)

batch_norm = True

metric_list = [nn.metrics.RMSE(), nn.metrics.MAE(), nn.metrics.R2Score()] # Only the first metric is used for training and early stopping

mpnn = models.MPNN(mp, 
                agg, 
                ffn, 
                batch_norm, 
                metric_list)

# Configure model checkpointing
checkpointing = ModelCheckpoint(
    "checkpoints",  # Directory where model checkpoints will be saved
    "best-{epoch}-{val_loss:.2f}",  # Filename format for checkpoints, including epoch and validation loss
    "val_loss",  # Metric used to select the best checkpoint (based on validation loss)
    mode="min",  # Save the checkpoint with the lowest validation loss (minimization objective)
    save_last=True,  # Always save the most recent checkpoint, even if it's not the best
)

logger = TensorBoardLogger(
    save_dir="logs/",
    default_hp_metric=False  # Avoid automatic hyperparameter logging
)

trainer = pl.Trainer(
    logger=logger,
    enable_checkpointing=True, # Use `True` if you want to save model checkpoints. The checkpoints will be saved in the `checkpoints` folder.
    enable_progress_bar=False,
    accelerator="auto",
    devices=1,
    max_epochs=1, # number of epochs to train for
    callbacks=[checkpointing], # Use the configured checkpoint callback
)

trainer.fit(mpnn, train_loader, val_loader)

results = trainer.test(dataloaders=test_loader, ckpt_path='best')

print(results)
```

**Expected behavior**
By removing: ```logger=logger``` and/or ```logger=True```, the code will work as usual.

**Error Stack Trace**
```
Traceback (most recent call last):
  File "/fred/oz310/BSIM/ML_studies/proper_ML_study/MPNN/prototype/improvement/example/example2.py", line 101, in <module>
    trainer.fit(mpnn, train_loader, val_loader)
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrup
t
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 970, in _run
    _log_hyperparams(self)
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/loggers/utilities.py", line 95, in _log_hyperparams
    logger.save()
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning_utilities/core/rank_zero.py", line 42, in wrapped_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/loggers/tensorboard.py", line 221, in save
    save_hparams_to_yaml(hparams_file, self.hparams)
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/core/saving.py", line 354, in save_hparams_to_yaml
    yaml.dump(v)
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/yaml/__init__.py", line 253, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/yaml/__init__.py", line 241, in dump_all
    dumper.represent(data)
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/yaml/representer.py", line 199, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/yaml/representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/yaml/representer.py", line 356, in represent_object
    return self.represent_mapping(tag+function_name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/yaml/representer.py", line 330, in represent_object
    dictitems = dict(dictitems)
                ^^^^^^^^^^^^^^^
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Environment**
```
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   2.1.0              pyhd8ed1ab_0    conda-forge
aimsim-core               2.2.1                    pypi_0    pypi
aiohttp                   3.9.5                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
alembic                   1.13.2             pyhd8ed1ab_0    conda-forge
astartes                  1.2.2                    pypi_0    pypi
astunparse                1.6.3              pyhd8ed1ab_2    conda-forge
attrs                     23.2.0                   pypi_0    pypi
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
brotli-python             1.1.0           py311hb755f60_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.34.3               heb4867d_0    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.18.0               hebfffa5_3    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py311hf29c0ef_0    conda-forge
chardet                   5.2.0           py311h38be061_1    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
chemprop                  2.1.0                    pypi_0    pypi
cloudpickle               3.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
colorlog                  6.8.2           py311h38be061_0    conda-forge
configargparse            1.7                      pypi_0    pypi
contourpy                 1.2.1           py311h9547e67_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
descriptastorus           2.8.0                    pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
expat                     2.6.2                h59595ed_0    conda-forge
filelock                  3.14.0                   pypi_0    pypi
flatbuffers               24.3.25              h59595ed_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.0          py311h331c9d8_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
freetype-py               2.3.0              pyhd8ed1ab_0    conda-forge
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.0                 pypi_0    pypi
future                    1.0.0              pyhd8ed1ab_0    conda-forge
gast                      0.5.5              pyhd8ed1ab_0    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
google-pasta              0.2.0              pyhd8ed1ab_1    conda-forge
greenlet                  3.0.3           py311hb755f60_0    conda-forge
grpcio                    1.65.5          py311h9c9ff8c_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5py                      3.12.1          nompi_py311hb639ac4_102    conda-forge
hdf5                      1.14.3          nompi_hdf9ad27_105    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
hyperopt                  0.2.7              pyhd8ed1ab_0    conda-forge
icu                       75.1                 he02047a_0    conda-forge
idna                      3.7                      pypi_0    pypi
importlib-metadata        8.0.0              pyha770c72_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
keras                     3.6.0              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py311h9547e67_1    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_3    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20240722.0      cxx17_h5888daf_1    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libblas                   3.9.0           22_linux64_openblas    conda-forge
libboost                  1.84.0               hb8260a3_6    conda-forge
libboost-python           1.84.0          py311h5510f57_3    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           22_linux64_openblas    conda-forge
libcurl                   8.10.1               hbbe4b11_0    conda-forge
libdeflate                1.20                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgfortran-ng            13.2.0               h69a702a_8    conda-forge
libgfortran5              13.2.0               h3d2ce59_8    conda-forge
libglib                   2.82.2               h2ff4ddf_0    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libgrpc                   1.65.5               hf5c653b_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           22_linux64_openblas    conda-forge
libnghttp2                1.64.0               h161d5f1_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.44               hadc24fc_0    conda-forge
libprotobuf               5.27.5               h5b01275_2    conda-forge
libre2-11                 2024.07.02           hbbce691_1    conda-forge
libsqlite                 3.47.0               hadc24fc_1    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              13.2.0               hc0a3c3a_7    conda-forge
libtiff                   4.6.0                h1dd3fc0_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.17.0               h8a09558_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.13.5               hb346dea_0    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
lightning                 2.2.5                    pypi_0    pypi
lightning-utilities       0.11.2                   pypi_0    pypi
mako                      1.3.5              pyhd8ed1ab_0    conda-forge
markdown                  3.6                pyhd8ed1ab_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5           py311h459d7ec_0    conda-forge
matplotlib-base           3.8.4           py311ha4ca890_2    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
mhfp                      1.9.6                    pypi_0    pypi
ml_dtypes                 0.4.0           py311h7db5c69_2    conda-forge
mordredcommunity          2.0.5                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi
multiprocess              0.70.16                  pypi_0    pypi
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
namex                     0.0.8              pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
networkx                  3.3                pyhd8ed1ab_1    conda-forge
numpy                     1.26.4          py311h64a7726_0    conda-forge
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.5.40                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
openbabel                 3.1.1           py311h8b422cb_9    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.4.0                hb9d3cd8_0    conda-forge
opt_einsum                3.4.0              pyhd8ed1ab_0    conda-forge
optree                    0.13.1          py311hd18a35c_1    conda-forge
optuna                    3.6.1              pyhd8ed1ab_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
padelpy                   0.1.16                   pypi_0    pypi
pandas                    2.2.2           py311h14de704_1    conda-forge
pandas-flavor             0.6.0                    pypi_0    pypi
patsy                     1.0.1              pyhff2d567_0    conda-forge
pcre2                     10.44                hba22ea6_2    conda-forge
pillow                    10.4.0          py311h4aec55e_1    conda-forge
pip                       24.0                     pypi_0    pypi
pixman                    0.43.2               h59595ed_0    conda-forge
protobuf                  5.27.5          py311hfdbb021_0    conda-forge
psutil                    5.9.8                    pypi_0    pypi
psycopg2-binary           2.9.9                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
py4j                      0.10.9.7           pyhd8ed1ab_0    conda-forge
pycairo                   1.26.0          py311h8feb60e_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pyfiglet                  0.8.post1                  py_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.9          hb806964_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python-flatbuffers        24.3.25            pyh59ac667_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytorch-lightning         2.2.5                    pypi_0    pypi
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py311h459d7ec_1    conda-forge
rdkit                     2023.9.6                 pypi_0    pypi
re2                       2024.07.02           h77b4e00_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reportlab                 4.1.0           py311h459d7ec_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rich                      13.9.4             pyhd8ed1ab_0    conda-forge
rlpycairo                 0.2.0              pyhd8ed1ab_0    conda-forge
scikit-learn              1.5.0                    pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
seaborn                   0.13.2               hd8ed1ab_2    conda-forge
seaborn-base              0.13.2             pyhd8ed1ab_2    conda-forge
setuptools                70.0.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.1                ha2e4443_0    conda-forge
sqlalchemy                2.0.30          py311h331c9d8_0    conda-forge
statsmodels               0.14.4          py311h9f3472d_0    conda-forge
sympy                     1.12.1                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tensorboard               2.17.1             pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.7.0           py311hafd3f86_2    conda-forge
tensorflow                2.17.0          cpu_py311h6ac8430_3    conda-forge
tensorflow-base           2.17.0          cpu_py311h78ee05f_3    conda-forge
tensorflow-estimator      2.17.0          cpu_py311h331965b_3    conda-forge
termcolor                 2.5.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.5.0                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
torch                     2.3.1                    pypi_0    pypi
torch-geometric           2.6.1                    pypi_0    pypi
torchmetrics              1.4.0.post0              pypi_0    pypi
tqdm                      4.66.4             pyhd8ed1ab_0    conda-forge
triton                    2.3.1                    pypi_0    pypi
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
werkzeug                  3.1.3              pyhff2d567_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
wrapt                     1.16.0          py311h9ecbd09_1    conda-forge
xarray                    2024.10.0                pypi_0    pypi
xlsxwriter                3.1.9              pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.10               h4f16b4b_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xorgproto            2024.1               hb9d3cd8_1    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.9.4                    pypi_0    pypi
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                h4ab18f5_1    conda-forge
zstandard                 0.23.0          py311hbc35293_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

**Comment by shihchengli** [comment]
This issue has been identified and reported in [github.com/pytorch/pytorch/issues/78720](https://github.com/pytorch/pytorch/issues/78720). Please track that issue.

**Comment by KnathanM** [comment]
May also have something to do with the version on pypi vs conda forge?

Your minimal example ran just fine for me. My torch and lightning version are:
```
pytorch                   2.4.0           cpu_mkl_py311h02aef37_101    conda-forge
pytorch-lightning         2.4.0              pyhd8ed1ab_0    conda-forge
```
For easy reference here are yours copied from above:
```
pytorch-lightning         2.2.5                    pypi_0    pypi
torch                     2.3.1                    pypi_0    pypi
```

**Comment by AquifersBSIM** [comment]
Thank you @shihchengli, @JacksonBurns, and @KnathanM for the valuable suggestions and help given. I have resolved the issue by upgrading to the latest pytorch-lightning and torch: This is most likely an outdated version issue.

```
pytorch-lightning         2.4.0                    pypi_0    pypi
torch                     2.4.0                    pypi_0    pypi
```
