### ISSUE TITLE
[v2 BUG]: Can't train with MveFFN or Evidential FFN without UnscaleTransform

### ISSUE THREAD

**Issue by jjacobgreen** [chemprop/chemprop#1107]
**Describe the bug**
An error is thrown when training with a `MVeFFN` or a `EvidentialFFN` predictor if no [`output_transform` is passed to the FFN Predictor](https://github.com/chemprop/chemprop/blob/b7385523aac79516b871f83feba5aeb4bc23c4da/chemprop/nn/predictors.py#L119). This is because the [default when no output transform is passed is `nn.Identity()`](https://github.com/chemprop/chemprop/blob/b7385523aac79516b871f83feba5aeb4bc23c4da/chemprop/nn/predictors.py#L136), which doesn't have a `transform_variance` method.

**Example(s)**
```python
from chemprop import data, models, nn
import lightning as pl
import pandas as pd

train_df = pd.DataFrame({"smiles": ["CCC", "CCC", "CCC"], "y": [1, 2, 3]})

train_data = [data.MoleculeDatapoint.from_smi(smi, y) for smi, y in zip(train_df["smiles"], train_df["y"])]
train_dataset = data.MoleculeDataset(train_data)
train_loader = data.build_dataloader(train_dataset, batch_size=2, shuffle=True)

model = models.MPNN(
    nn.BondMessagePassing(), 
    nn.MeanAggregation(), 
    nn.MveFFN(),
    # nn.UnscaleTransform([0], [1]),  # works when commented in, throws error when commented out
)

trainer = pl.Trainer(
    logger=False,
    enable_checkpointing=True,
    enable_progress_bar=True,
    accelerator="auto",
    devices=1,
    max_epochs=20,
)

trainer.fit(model, train_loader)
```

**Expected behavior**
It's possible to train with a `MveFFN` or a `EvidentialFFN` without being **required** to use an unscaling transform.

**Error Stack Trace**
```
Traceback (most recent call last):
  File "/development/ml/chemprop_example.py", line 27, in <module>
    trainer.fit(model, train_loader)
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 981, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 1025, in _run_stage
    self.fit_loop.run()
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/fit_loop.py", line 205, in run
    self.advance()
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 140, in run
    self.advance(data_fetcher)
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 250, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 190, in run
    self._optimizer_step(batch_idx, closure)
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 268, in _optimizer_step
    call._call_lightning_module_hook(
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 167, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/core/module.py", line 1306, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/core/optimizer.py", line 153, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/strategies/strategy.py", line 238, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/plugins/precision/precision.py", line 122, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/torch/optim/lr_scheduler.py", line 75, in wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/torch/optim/optimizer.py", line 385, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/torch/optim/adam.py", line 146, in step
    loss = closure()
           ^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/plugins/precision/precision.py", line 108, in _wrap_closure
    closure_result = closure()
                     ^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 144, in __call__
    self._result = self.closure(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 129, in closure
    step_output = self._step_fn()
                  ^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 317, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 319, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/lightning/pytorch/strategies/strategy.py", line 390, in training_step
    return self.lightning_module.training_step(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/chemprop/models/model.py", line 148, in training_step
    preds = self.predictor.train_step(Z)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/chemprop/nn/predictors.py", line 180, in forward
    var = self.output_transform.transform_variance(var)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uv/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Identity' object has no attribute 'transform_variance'
```

**Screenshots**
N/A

**Environment**
- 3.12.7
- package versions:
 ```
chemprop==2.1.0
pytorch-lightning==2.4.0
lightning==2.4.0
numpy==1.26.4
torch==2.2.2
rdkit==2024.3.6
scikit-learn==1.5.2
scipy==1.12.0
astartes==1.3.0
configargparse==1.7
rich==13.9.4
descriptastorus==2.8.0
```
- OS
Debian (docker) [nvidia/cuda:12.6.2-cudnn-runtime-ubuntu22.04](https://hub.docker.com/layers/nvidia/cuda/12.6.2-cudnn-runtime-ubuntu22.04/images/sha256-219312400e078c7129db2ecc0ea3308406ac38392de92d3dabe22ef4e68a9f70?context=explore)

**Checklist**
- [X] all dependencies are satisifed: `conda list` or `pip list` shows the packages listed in the `pyproject.toml`
- [X] the unit tests are working: `pytest -v` reports no errors

**Additional context**
Potential fixes. Happy to open a PR if it's a reproducible issue and depending on the advised approach to fix.

1. In `chemprop/nn/transforms.py`:
Something to the effect of:
```python
class IdentityUnscaleTransform(_ScaleTransformMixin):
    def forward(self, X: Tensor) -> Tensor:
        return X

    def transform_variance(self, var: Tensor) -> Tensor:
        return var
```

3. Can just check if the method exists and only apply it if it does. E.g. in In `chemprop/nn/transforms.py#L164`:

```python
if hasattr(self.output_transform, "transform_variance"):
    var = self.output_transform.transform_variance(var)
```

**Comment by JacksonBurns** [comment]
@shihchengli

**Comment by shihchengli** [comment]
@jjacobgreen thanks for reporting this bug. I have opened an PR #1108 to fix it. Feel free to try my branch ([shihchengli:fix_output_transform](https://github.com/shihchengli/chemprop/tree/fix_output_transform)) to see if it can address the issue.
