### ISSUE TITLE
Issue with masking data in multi-task training

### ISSUE THREAD

**Issue by mmagithub** [chemprop/chemprop#1122]
Hi,

I have a question about multi-task training in Chemprop. Does it require a specific proportion of non-NaN values in any of the target columns? My understanding is that Chemprop masks NaN values by default during training.

I am attempting to run a hyperparameter optimization job with a multi-task dataset containing three properties (prop1, prop2, prop3). Some values are missing (NaN) for certain molecules in some columns.

Here is the command I am using:

`chemprop train --data-path toy_data.csv --task-type regression --target-columns prop1 prop2 prop3 --metrics mse --splits-column splits --smiles-columns SMILES --epochs 50 --num-workers 2 --ensemble-size 1 --loss-function mse --depth 4 --message-hidden-dim 300 --ffn-hidden-dim 300 --ffn-num-layers 2 --dropout 0.21777181937570478 --batch-size 8 --activation LeakyReLU --aggregation sum --aggregation-norm 6.957056202129309 --save-dir hyperopt_results/trial_20241213_125435
`

However, I am encountering the following error:

`
2024-12-14T10:56:35 - INFO:chemprop.cli.main - Running in mode 'train' with args: {'smiles_columns': ['SMILES'], 'reaction_columns': None, 'no_header_row': False, 'num_workers': 2, 'batch_size': 8, 'accelerator': 'auto', 'devices': 'auto', 'rxn_mode': 'REAC_DIFF', 'multi_hot_atom_featurizer_mode': 'V2', 'keep_h': False, 'add_h': False, 'molecule_featurizers': None, 'descriptors_path': None, 'no_descriptor_scaling': False, 'no_atom_feature_scaling': False, 'no_atom_descriptor_scaling': False, 'no_bond_feature_scaling': False, 'atom_features_path': None, 'atom_descriptors_path': None, 'bond_features_path': None, 'config_path': None, 'data_path': PosixPath('toy_data.csv'), 'output_dir': PosixPath('hyperopt_results/trial_20241213_125435'), 'remove_checkpoints': False, 'checkpoint': None, 'freeze_encoder': False, 'model_frzn': None, 'frzn_ffn_layers': 0, 'ensemble_size': 1, 'message_hidden_dim': 300, 'message_bias': False, 'depth': 4, 'undirected': False, 'dropout': 0.21777181937570478, 'mpn_shared': False, 'activation': 'LEAKYRELU', 'aggregation': 'sum', 'aggregation_norm': 6.957056202129309, 'atom_messages': False, 'ffn_hidden_dim': 300, 'ffn_num_layers': 2, 'batch_norm': False, 'multiclass_num_classes': 3, 'weight_column': None, 'target_columns': ['prop1', 'prop2', 'prop3'], 'ignore_columns': None, 'no_cache': False, 'splits_column': 'splits', 'task_type': 'regression', 'loss_function': 'mse', 'v_kl': 0.0, 'eps': 1e-08, 'alpha': 0.1, 'metrics': ['mse'], 'tracking_metric': 'val_loss', 'show_individual_scores': False, 'task_weights': None, 'warmup_epochs': 2, 'init_lr': 0.0001, 'max_lr': 0.001, 'final_lr': 0.0001, 'epochs': 50, 'patience': None, 'grad_clip': None, 'class_balance': False, 'split': 'RANDOM', 'split_sizes': [0.8, 0.1, 0.1], 'split_key_molecule': 0, 'num_replicates': 1, 'num_folds': None, 'save_smiles_splits': False, 'splits_file': None, 'data_seed': 0, 'pytorch_seed': None}
Wrote config file to hyperopt_results/trial_20241213_125435/config.toml
2024-12-14T10:56:35 - INFO:chemprop.cli.train - Pulling data from file: toy_data.csv
[10:56:37] Explicit valence for atom # 5 N, 4, is greater than permitted
Traceback (most recent call last):
  File "/opt/conda/envs/chemprop_env/bin/chemprop", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/chemprop_env/lib/python3.11/site-packages/chemprop/cli/main.py", line 85, in main
    func(args)
  File "/opt/conda/envs/chemprop_env/lib/python3.11/site-packages/chemprop/cli/train.py", line 89, in func
    main(args)
  File "/opt/conda/envs/chemprop_env/lib/python3.11/site-packages/chemprop/cli/train.py", line 1258, in main
    splits = build_splits(args, format_kwargs, featurization_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/chemprop_env/lib/python3.11/site-packages/chemprop/cli/train.py", line 742, in build_splits
    all_data = build_data_from_files(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/chemprop_env/lib/python3.11/site-packages/chemprop/cli/utils/parsing.py", line 344, in build_data_from_files
    mol_data, rxn_data = make_datapoints(
                         ^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/chemprop_env/lib/python3.11/site-packages/chemprop/cli/utils/parsing.py", line 269, in make_datapoints
    mol_data = [
               ^
  File "/opt/conda/envs/chemprop_env/lib/python3.11/site-packages/chemprop/cli/utils/parsing.py", line 270, in <listcomp>
    [
  File "/opt/conda/envs/chemprop_env/lib/python3.11/site-packages/chemprop/cli/utils/parsing.py", line 271, in <listcomp>
    MoleculeDatapoint(
  File "<string>", line 14, in __init__
  File "/opt/conda/envs/chemprop_env/lib/python3.11/site-packages/chemprop/data/datapoints.py", line 79, in __post_init__
    raise ValueError("Input molecule was `None`!")
ValueError: Input molecule was `None`!`
#########

Could you help me understand, If there are any specific requirements for handling missing (NaN) values in multi-task training?

Running the same command on a different data with different proportion of missing values in some column worked.

I am also noticing that in the "INFO:chemprop.cli.main" command printed, split is set to RANDOM, eventhough I am asking for "--splits-column splits" in the main command.

Best regards,
Marawan

**Comment by JacksonBurns** [comment]
chemprop should mask missing target values, but I think you have a missing or invalid SMILES in your input file.

The printed splitting in the log is just the default option - behind the scenes it is using your splits, but we don't have an option to represent that in the splitting API so it just shows the default.

**Comment by mmagithub** [comment]
Thanks, Jackson. I’m quite confident about the data. My understanding is that Chemprop will automatically drop molecules with faulty SMILES if they exist. As I mentioned earlier, I tested the code using a subset of the same data with varying proportions of missing target values, and it worked successfully in those cases. Do you suspect any other issue than the data itself is faulty ?

**Comment by mmagithub** [comment]
I identified the root cause of the issue—it was a single molecule with improper N-oxide protonation states: CC1=CC=C[NH+2]([O-])C1. Once I removed this molecule from the dataset, the problem was resolved.

This molecule was prepared using RDKit and provided as-is. I'm unsure if this behavior is the expected behavior for Chemprop, but it could become problematic when working with very large datasets. Fortunately, the dataset I used was relatively small, with only a few thousand molecules.

**Comment by JacksonBurns** [comment]
Nope, chemprop won't drop SMILES. See this example input file:
```csv
smiles,target
[],0
C,1
```

which when run with `chemprop train -i example.csv` produces the same error you see because `[]` is not a valid SMILES string and RDKit returns `None`.

```bash
(chemprop_v2_live) PS C:\Users\ChemEGrad2022\Desktop> chemprop train -i example.csv
2024-12-16T11:41:03 - INFO:chemprop.cli.main - Running in mode 'train' with args: {'smiles_columns': None, 'reaction_columns': None, 'no_header_row': False, 'num_workers': 0, 'batch_size': 64, 'accelerator': 'auto', 'devices': 'auto', 'rxn_mode': 'REAC_DIFF', 'multi_hot_atom_featurizer_mode': 'V2', 'keep_h': False, 'add_h': False, 'molecule_featurizers': None, 'descriptors_path': None, 'no_descriptor_scaling': False, 'no_atom_feature_scaling': False, 'no_atom_descriptor_scaling': False, 'no_bond_feature_scaling': False, 'atom_features_path': None, 'atom_descriptors_path': None, 'bond_features_path': None, 'config_path': None, 'data_path': WindowsPath('example.csv'), 'output_dir': None, 'remove_checkpoints': False, 'checkpoint': None, 'freeze_encoder': False, 'model_frzn': None, 'frzn_ffn_layers': 0, 'ensemble_size': 1, 'message_hidden_dim': 300, 'message_bias': False, 'depth': 3, 'undirected': False, 'dropout': 0.0, 'mpn_shared': False, 'activation': 'RELU', 'aggregation': 'norm', 'aggregation_norm': 100, 'atom_messages': False, 'ffn_hidden_dim': 300, 'ffn_num_layers': 1, 'batch_norm': False, 'multiclass_num_classes': 3, 'weight_column': None, 'target_columns': None, 'ignore_columns': None, 'no_cache': False, 'splits_column': None, 'task_type': 'regression', 'loss_function': None, 'v_kl': 0.0, 'eps': 1e-08, 'alpha': 0.1, 'metrics': None, 'tracking_metric': 'val_loss', 'show_individual_scores': False, 'task_weights': None, 'warmup_epochs': 2, 'init_lr': 0.0001, 'max_lr': 0.001, 'final_lr': 0.0001, 'epochs': 50, 'patience': None, 'grad_clip': None, 'class_balance': False, 'split': 'RANDOM', 'split_sizes': [0.8, 0.1, 0.1], 'split_key_molecule': 0, 'num_replicates': 1, 'num_folds': None, 'save_smiles_splits': False, 'splits_file': None, 'data_seed': 0, 'pytorch_seed': None}
Wrote config file to chemprop_training\example\2024-12-16T11-41-03\config.toml
2024-12-16T11:41:03 - INFO:chemprop.cli.train - Pulling data from file: example.csv
[11:41:03] SMILES Parse Error: syntax error while parsing: []
[11:41:03] SMILES Parse Error: Failed parsing SMILES '[]' for input: '[]'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ChemEGrad2022\mambaforge\envs\chemprop_v2_live\Scripts\chemprop.exe\__main__.py", line 7, in <module>
  File "C:\Users\ChemEGrad2022\mambaforge\envs\chemprop_v2_live\Lib\site-packages\chemprop\cli\main.py", line 85, in main
    func(args)
  File "C:\Users\ChemEGrad2022\mambaforge\envs\chemprop_v2_live\Lib\site-packages\chemprop\cli\train.py", line 89, in func
    main(args)
  File "C:\Users\ChemEGrad2022\mambaforge\envs\chemprop_v2_live\Lib\site-packages\chemprop\cli\train.py", line 1258, in main
    splits = build_splits(args, format_kwargs, featurization_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ChemEGrad2022\mambaforge\envs\chemprop_v2_live\Lib\site-packages\chemprop\cli\train.py", line 742, in build_splits
    all_data = build_data_from_files(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ChemEGrad2022\mambaforge\envs\chemprop_v2_live\Lib\site-packages\chemprop\cli\utils\parsing.py", line 344, in build_data_from_files
    mol_data, rxn_data = make_datapoints(
                         ^^^^^^^^^^^^^^^^
  File "C:\Users\ChemEGrad2022\mambaforge\envs\chemprop_v2_live\Lib\site-packages\chemprop\cli\utils\parsing.py", line 269, in make_datapoints
    mol_data = [
               ^
  File "C:\Users\ChemEGrad2022\mambaforge\envs\chemprop_v2_live\Lib\site-packages\chemprop\cli\utils\parsing.py", line 270, in <listcomp>
    [
  File "C:\Users\ChemEGrad2022\mambaforge\envs\chemprop_v2_live\Lib\site-packages\chemprop\cli\utils\parsing.py", line 271, in <listcomp>
    MoleculeDatapoint(
  File "<string>", line 14, in __init__
  File "C:\Users\ChemEGrad2022\mambaforge\envs\chemprop_v2_live\Lib\site-packages\chemprop\data\datapoints.py", line 79, in __post_init__
    raise ValueError("Input molecule was `None`!")
ValueError: Input molecule was `None`!
```

You need to identify which SMILES are invalid

**Comment by mmagithub** [comment]
Here is a script that cleaned my data, you can see if it can be added to the main repo. The caveat is that it must be ran through the exact same rdkit that Chemprop uses internally. 

<
import pandas as pd
import os
import sys
from rdkit import Chem
from rdkit.Chem import SanitizeMol, SanitizeFlags
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("rdkit")

def validate_smiles(smiles):

    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            logger.warning(f"Invalid SMILES (cannot parse): {smiles}")
            return False

        SanitizeMol(mol, sanitizeOps=SanitizeFlags.SANITIZE_ALL)
        return True
    except Exception as e:
        logger.warning(f"SMILES validation failed for: {smiles}. Error: {e}")
        return False


def clean_dataset(input_csv, smiles_column="SMILES"):
    """
    Args:
    - input_csv: Path to the input CSV file.
    - smiles_column: Name of the column containing SMILES strings.
    """
    df = pd.read_csv(input_csv)

    print(f"Validating SMILES strings in {input_csv}...")
    df["is_valid"] = df[smiles_column].apply(validate_smiles)

    valid_df = df[df["is_valid"]].drop(columns=["is_valid"])

    base_name = os.path.basename(input_csv)
    output_csv = os.path.join(os.path.dirname(input_csv), f"cleaned_{base_name}")

    valid_df.to_csv(output_csv, index=False)
    print(f"Cleaned dataset saved to {output_csv}")
    print(f"Number of valid molecules: {len(valid_df)}")
    print(f"Number of invalid molecules removed: {len(df) - len(valid_df)}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python clean_dataset.py <input_csv>")
        sys.exit(1)

    input_csv = sys.argv[1]
    
    clean_dataset(input_csv)
>
