### ISSUE TITLE
[v1 BUG]: error and cost much time

### ISSUE THREAD

**Issue by jia-huang** [chemprop/chemprop#1132]
When running the following command, the following error message appears, but the program still runs and completes successfully. What is the cause of this error? Will this error affect the final classification performance of the model?

Additionally, for a dataset with 30,000 entries, it takes 3 hours to train one model and complete one epoch. What could be the reason for this? Is this normal? My computer configuration is as follows:

**command:**
```
chemprop_train --dataset_type classification \
--save_dir ../chemprop_model/SD1_activity_checkpoints_3 \
--features_generator rdkit_2d_normalized --no_features_scaling \
--epochs 30 --ensemble_size 10 --extra_metrics prc-auc --data_path D:/Huangjia/shenwuxinxi/chemprop_data/Nature/SD1_activity_train.csv \
--separate_val_path D:/Huangjia/shenwuxinxi/chemprop_data/Nature/SD1_activity_val.csv \
--separate_test_path D:/Huangjia/shenwuxinxi/chemprop_data/Nature/SD1_activity_test.csv \
--target_columns Lable \
--smiles_columns SMILES \
--config_path shoudong-paper2_1-config.json
```

**JSON file (model configuration):**
```
{
    "message-hidden-dim": 1600,
    "depth": 5,
    "dropout": 0.15,
    "ffn-num-layers": 1,
    "ffn-hidden-dim": 1600
}
```

**The computer configuration is as follows:**
13th Gen Intel(R) Core(TM) i9-13900K   3.00 GHz
128 GB (128 GB 可用)
4090 显卡

**Error message:**
```
Could not compute EState_VSA3 for molecule
Traceback (most recent call last):
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\descriptastorus\descriptors\rdNormalizedDescriptors.py", line 81, in applyNormalizedFunc
    return cdfs[name](rdDescriptors.applyFunc(funcs, name,m))
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\descriptastorus\descriptors\rdNormalizedDescriptors.py", line 68, in cdf
    v = dist.cdf(np.clip(v, minV, maxV), loc=loc, scale=scale, *arg)
  File "<__array_function__ internals>", line 200, in clip
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\core\fromnumeric.py", line 2180, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\core\fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\core\fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\core\_methods.py", line 161, in _clip
    return _clip_dep_invoke_with_casting(
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\core\_methods.py", line 115, in _clip_dep_invoke_with_casting
    return ufunc(*args, out=out, **kwargs)
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
function application failed (EState_VSA4->C=CCOC(=O)[C@@H]1[C@H]2C(=O)O[C@H](c3ccccc3)[C@H](c3ccccc3)N2[C@H](c2ccccc2OCCO)[C@@]12C(=O)Nc1ccc(I)cc12)
Traceback (most recent call last):
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\descriptastorus\descriptors\rdDescriptors.py", line 432, in applyFunc
    return functions[name](m)
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\rdkit\Chem\EState\EState_VSA.py", line 110, in EState_VSA_bin
    return EState_VSA_(mol, force=False)[nbin]
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\rdkit\Chem\EState\EState_VSA.py", line 72, in EState_VSA_
    propContribs = EStateIndices_(mol, force=force)
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\rdkit\Chem\EState\EState.py", line 48, in EStateIndices
    Is = numpy.zeros(nAtoms, numpy.float)
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `n
p.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Could not compute EState_VSA4 for molecule
Traceback (most recent call last):
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\descriptastorus\descriptors\rdNormalizedDescriptors.py", line 81, in applyNormalizedFunc
    return cdfs[name](rdDescriptors.applyFunc(funcs, name,m))
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\descriptastorus\descriptors\rdNormalizedDescriptors.py", line 68, in cdf
    v = dist.cdf(np.clip(v, minV, maxV), loc=loc, scale=scale, *arg)
  File "<__array_function__ internals>", line 200, in clip
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\core\fromnumeric.py", line 2180, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\core\fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\core\fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\core\_methods.py", line 161, in _clip
    return _clip_dep_invoke_with_casting(
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\core\_methods.py", line 115, in _clip_dep_invoke_with_casting
    return ufunc(*args, out=out, **kwargs)
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
Traceback (most recent call last):
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\descriptastorus\descriptors\rdNormalizedDescriptors.py", line 81, in applyNormalizedFunc
    return cdfs[name](rdDescriptors.applyFunc(funcs, name,m))
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\descriptastorus\descriptors\rdNormalizedDescriptors.py", line 68, in cdf
    v = dist.cdf(np.clip(v, minV, maxV), loc=loc, scale=scale, *arg)
  File "<__array_function__ internals>", line 200, in clip
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\core\fromnumeric.py", line 2180, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\core\fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\core\fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\core\_methods.py", line 161, in _clip
    return _clip_dep_invoke_with_casting(
  File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\numpy\core\_methods.py", line 115, in _clip_dep_invoke_with_casting
    return ufunc(*args, out=out, **kwargs)
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
```

**Comment by KnathanM** [comment]
Hi @jia-huang, 

Looks like the error you are having originates from `descriptastorus`. 
```
File "C:\Users\PS\miniconda3\envs\hjpy38mri\lib\site-packages\descriptastorus\descriptors\rdNormalizedDescriptors.py", line 81, in applyNormalizedFunc
    return cdfs[name](rdDescriptors.applyFunc(funcs, name,m))
```
You could try generating the rdkit features first and then pass them into the model using `--features_path`. 

But this could also be a versioning issue of `descriptastorus` or `numpy` because `descriptastorus` works for me with the SMILES in your error traceback.
```
from chemprop.featurizers.molecule import V1RDKit2DNormalizedFeaturizer
from rdkit import Chem
featurizer = V1RDKit2DNormalizedFeaturizer()
smi = "C=CCOC(=O)[C@@H]1[C@H]2C(=O)O[C@H](c3ccccc3)[C@H](c3ccccc3)N2[C@H](c2ccccc2OCCO)[C@@]12C(=O)Nc1ccc(I)cc12"
mol = Chem.MolFromSmiles(smi)
featurizer(mol)
``` 
This uses Chemprop v2, but I believe it calls `descriptastorus` in the same was as v1. 

You could also try [migrating](https://docs.google.com/spreadsheets/u/3/d/e/2PACX-1vRshySIknVBBsTs5P18jL4WeqisxDAnDE5VRnzxqYEhYrMe4GLS17w5KeKPw9sged6TmmPZ4eEZSTIy/pubhtml) to Chemprop v2 and see if your error persists. 

As for why training takes so long, that's not typical. You could use a GPU profiler (you can find one for your type of GPU on Google probably) to see if it is being used properly.
