### ISSUE TITLE
Issue with scaffold_to_smiles function

### ISSUE THREAD

**Issue by Arkkienkeli** [chemprop/chemprop#158]
Hello, 
I have an issue with `scaffold_to_smiles` function.  The ChemProp version is from 31 March 2021.

I use it in a similar way like in https://github.com/chemprop/chemprop/blob/master/scripts/create_crossval_splits.py
and call it this way (`data` is `MoleculeDataset` here) :
```
scaffold_to_indices = scaffold_to_smiles(data.mols(), use_indices=True)
```
and I get an error:

```
Traceback (most recent call last):
  File "./chemprop/scaffold_split.py", line 70, in <module>
    create_crossval_splits()
  File "./chemprop/scaffold_split.py", line 64, in create_crossval_splits
    fold_indices = split_indices(all_indices, num_folds=5, data=data)
  File "./chemprop/scaffold_split.py", line 24, in split_indices
    scaffold_to_indices = scaffold_to_smiles(data.mols(), use_indices=True)
  File "./chemprop/chemprop/data/scaffold.py", line 41, in scaffold_to_smiles
    scaffold = generate_scaffold(mol)
  File "./chemprop/chemprop/data/scaffold.py", line 24, in generate_scaffold
    scaffold = MurckoScaffold.MurckoScaffoldSmiles(mol=mol, includeChirality=include_chirality)
  File "/home/.conda/envs/chemprop/lib/python3.9/site-packages/rdkit/Chem/Scaffolds/MurckoScaffold.py", line 109, in MurckoScaffoldSmiles
    scaffold = GetScaffoldForMol(mol)
  File "/home/.conda/envs/chemprop/lib/python3.9/site-packages/rdkit/Chem/Scaffolds/MurckoScaffold.py", line 73, in GetScaffoldForMol
    res = Chem.MurckoDecompose(mol)
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdmolops.MurckoDecompose(list)
did not match C++ signature:
    MurckoDecompose(RDKit::ROMol mol)
```
There was a similar issue: https://github.com/chemprop/chemprop/issues/98
Do I use it correctly or is it a bug?
Thank you!

**Comment by hesther** [comment]
Thanks for reporting, this is another bug that must have been missed when we introduced multiple molecules input. I will look into and correct it shortly, but for your script, it should be sufficient to do:

`scaffold_to_indices = scaffold_to_smiles(data.mols(flatten=True), use_indices=True)`

(in case you have single-molecule input. If you have multi-molecule input, I believe scaffold splitting is not supported).

Let me know if this has worked.

**Comment by Arkkienkeli** [comment]
@hesther 
Yes, this workaround helped. Thank you!

**Comment by hesther** [comment]
@Arkkienkeli You are welcome, thanks again for reporting!
