### ISSUE TITLE
bug report in scripts/split_data.py

### ISSUE THREAD

**Issue by sky1ove** [chemprop/chemprop#186]
When the split_type is random as below, the python script works fine
python scripts/split_data.py --data_path clintox2.csv --save_dir split --split_type random

however, when it is changed to scaffold_balanced in split_type, as below, there is an error
python scripts/split_data.py --data_path clintox2.csv --save_dir split --split_type scaffold_balanced

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1484/1484 [00:00<00:00, 731415.64it/s]
  0%|▌                                                                                                                        | 7/1484 [00:00<00:00, 7206.71it/s]
Traceback (most recent call last):
  File "D:\Users\lcai8\PycharmProjects\drug_discovery\scripts\split_data.py", line 67, in <module>
    run_split_data(Args().parse_args())
  File "D:\Users\lcai8\PycharmProjects\drug_discovery\scripts\split_data.py", line 49, in run_split_data
    train, val, test = split_data(
  File "D:\Users\lcai8\PycharmProjects\drug_discovery\chemprop\data\utils.py", line 481, in split_data
    return scaffold_split(data, sizes=sizes, balanced=True, seed=seed, logger=logger)
  File "D:\Users\lcai8\PycharmProjects\drug_discovery\chemprop\data\scaffold.py", line 82, in scaffold_split
    scaffold_to_indices = scaffold_to_smiles(data.mols(flatten=True), use_indices=True)
  File "D:\Users\lcai8\PycharmProjects\drug_discovery\chemprop\data\scaffold.py", line 44, in scaffold_to_smiles
    scaffold = generate_scaffold(mol)
  File "D:\Users\lcai8\PycharmProjects\drug_discovery\chemprop\data\scaffold.py", line 27, in generate_scaffold
    scaffold = MurckoScaffold.MurckoScaffoldSmiles(mol = mol, includeChirality = include_chirality)
  File "D:\ProgramData\Anaconda3\envs\drug\lib\site-packages\rdkit\Chem\Scaffolds\MurckoScaffold.py", line 108, in MurckoScaffoldSmiles
    raise ValueError('No molecule provided')
ValueError: No molecule provided

**Comment by hesther** [comment]
Dear @sky1ove, are you using the newest version of chemprop? And did you install the pre-compiled package from conda or did you clone the GitHub repository? I just tried to reproduce your results, and the splitting works fine with all options.

**Comment by sailseem** [comment]
well, I bummed into the same issue when executed --split_type scaffold_balanced. I just downloaded the 1.3.1 latest repo. Thanks!

**Comment by hesther** [comment]
Hi @sailseem, sorry for the VERY late response, please make a new issue if you want to report something, otherwise it often gets overlooked (like this one, I just randomly discovered it, sorry!). 

I just tried to run this again, and cannot recover your error. If you still have it, could you comment with your Python version,  OS (Mac, Linux, etc) and which dataset you used? I will try to track down the error then.
