### ISSUE TITLE
error at atom_messages = True and undirected = True

### ISSUE THREAD

**Issue by jinserk** [chemprop/chemprop#21]
Hi, 

Here I got an error when I gave the options:
```
python train.py --data_path <data-csv> --dataset_type regression --save_dir test2 --atom_messages --undirected
```

```
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    cross_validate(args, logger)
  File "/home/jinserk/kyu/chemprop/chemprop/train/cross_validate.py", line 29, in cross_validate
    model_scores = run_training(args, logger)
  File "/home/jinserk/kyu/chemprop/chemprop/train/run_training.py", line 180, in run_training
    n_iter = train(
  File "/home/jinserk/kyu/chemprop/chemprop/train/train.py", line 71, in train
    preds = model(batch, features_batch)
  File "/home/jinserk/.pyenv/versions/3.8.2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jinserk/kyu/chemprop/chemprop/models/model.py", line 88, in forward
    output = self.ffn(self.encoder(*input))
  File "/home/jinserk/.pyenv/versions/3.8.2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jinserk/kyu/chemprop/chemprop/models/mpn.py", line 187, in forward
    output = self.encoder.forward(batch, features_batch)
  File "/home/jinserk/kyu/chemprop/chemprop/models/mpn.py", line 102, in forward
    message = (message + message[b2revb]) / 2
RuntimeError: The size of tensor a (3616) must match the size of tensor b (8509) at non-singleton dimension 0
```
I'd like to know why this is happend.
Thank you!

**Comment by swansonk14** [comment]
Hi @jinserk, thank you for the question! I realize we had only ever tried `atom_messages` and `undirected` separately so we hadn't considered the possibility of using both at the same time.

I thought about it and conceptually, I just realized that `undirected` is technically redundant when `atom_messages` are being used. When `atom_messages` are used, the bond features are changed so they only consist of features specifically about that bond, rather than both features of that bond and features of one of the atoms the bond is connected to (this is the aspect that makes the default implementation directed). Thus, when `atom_messages` are used, the bond features are by their nature undirected and so there's no need to specify the `undirected` flag.

Rather than try to fix the `MPN` code to handle both flags simultaneously, I'm going to add a line to prevent the user from setting both flags at once: https://github.com/chemprop/chemprop/commit/f762f725815b02b9777bed45347135a10e320dac. That commit is currently in a different branch but I plan to merge it into master soon.
