### ISSUE TITLE
predict with --reaction?

### ISSUE THREAD

**Issue by jugoetz** [chemprop/chemprop#231]
Hi.

I was surprised to find that the --reaction flag does not work for chemprop_predict and so predictions for reactionSMILES can not be made. Trying to run a prediction without the --reaction flag raises an error (as should be expected). Under the hood, the functionality must be there for chemprop_train to give you scores, so this is probably just a question of connecting the two parts.

But as the JCIM paper does many of these predictions, maybe I am just missing how this is implemented?

**Comment by cjmcgill** [comment]
You should not need to specify --reaction when you're doing the prediction job because the reaction settings are stored in the checkpoint file that you are using. Could you share the error that you get when you try to predict from the reaction checkpoint?

**Comment by hesther** [comment]
Hi @jugoetz , I agree with Charles, you do not need to specify `--reaction` If you load a checkpoint that was trained with that option. I used the prediction script with the reaction option many times, so I guess there might be a simple reason for the error you see. 

To test the functionality, you could train a dummy model on some test data:
`python train.py --data_path tests/data/reaction_regression.csv --dataset_type regression --reaction --explicit_h --save_dir test_reaction --epochs 2`

and then predict:
`python predict.py --test_path tests/data/reaction_regression.csv --checkpoint_dir test_reaction --preds_path test.csv`

which works fine for me (writes the predictions to test.csv). Could you try to run this?
What OS and Python version do you use? We have had some problems with macOS and Python>=3.8 recently due to an under-the-hood change of how globals are treated when multi-threading (which causes problems with some options, e.g. the reaction option)

**Comment by jugoetz** [comment]
Hi, and thanks for the prompt replies! 

So the error I am getting traces back to the `MolGraph` from `featurization.py` landing in the `if not self.is_reaction` clause which it shouldn't. This happens for both the data I has tried to use and for @hesther's commands using the test data.

Here's the full traceback (from the `python predict.py` command):

```
Traceback (most recent call last):                                                                                                                               
  File "/Users/julian/chemprop/predict.py", line 6, in <module>
    chemprop_predict()
  File "/Users/julian/chemprop/chemprop/train/make_predictions.py", line 287, in chemprop_predict
    make_predictions(args=PredictArgs().parse_args())
  File "/Users/julian/chemprop/chemprop/utils.py", line 574, in wrap
    result = func(*args, **kwargs)
  File "/Users/julian/chemprop/chemprop/train/make_predictions.py", line 277, in make_predictions
    avg_preds = predict_and_save(args, train_args, test_data, task_names, num_tasks, test_data_loader, full_data, full_to_valid_indices, models, scalers)
  File "/Users/julian/chemprop/chemprop/train/make_predictions.py", line 154, in predict_and_save
    model_preds = predict(
  File "/Users/julian/chemprop/chemprop/train/predict.py", line 27, in predict
    for batch in tqdm(data_loader, disable=disable_progress_bar, leave=False):
  File "/Users/julian/.pyenv/versions/anaconda3-2020.07/envs/chemprop/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/Users/julian/.pyenv/versions/anaconda3-2020.07/envs/chemprop/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/Users/julian/.pyenv/versions/anaconda3-2020.07/envs/chemprop/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/Users/julian/.pyenv/versions/anaconda3-2020.07/envs/chemprop/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/Users/julian/.pyenv/versions/anaconda3-2020.07/envs/chemprop/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/julian/.pyenv/versions/anaconda3-2020.07/envs/chemprop/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/julian/.pyenv/versions/anaconda3-2020.07/envs/chemprop/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/Users/julian/chemprop/chemprop/data/data.py", line 604, in construct_molecule_batch
    data.batch_graph()  # Forces computation and caching of the BatchMolGraph for the molecules
  File "/Users/julian/chemprop/chemprop/data/data.py", line 303, in batch_graph
    mol_graph = MolGraph(m, d.atom_features, d.bond_features,
  File "/Users/julian/chemprop/chemprop/features/featurization.py", line 322, in __init__
    self.f_atoms = [atom_features(atom) for atom in mol.GetAtoms()]
AttributeError: 'tuple' object has no attribute 'GetAtoms'
```

Indeed I use macOS 11 and Python3.9, so that might be causing the trouble. As you mentioned multi-threading at the problem, I tried `--num_workers 1`. No change.  I also tried forcing it through the featurization step by hardcoding `self.is_reaction = True` and that made me pass that stage. But then I I got an error downstream in the torch part. Not sure if related. 

I'll try to get my hands on a Windows machine tomorrow, for comparison. If you know of any workaround for the macOS problem, please let me know.

**Comment by hesther** [comment]
I am currently running tests. If this is a macOS/Python version issue (which it might be, since `is_reaction` seems to be wrong), it can be solved by downgrading to Python 3.7.

**Comment by hesther** [comment]
@jugoetz  You can also test by avoiding multi-threading (careful, this is via `--num_workers 0` not `--num_workers 1` (which still spawns one process, which makes the globals reinitialise wrongly on Macos with Python >=3.8))

**Comment by jugoetz** [comment]
I can confirm that both downgrading to `python==3.7` or specifying `--num_workers 0` in Python3.9 solves the problem.

Thanks for your help! 👍
