### ISSUE TITLE
chemprop_train and chemprop_fingerprint with atom_descriptors

### ISSUE THREAD

**Issue by MariBerry** [chemprop/chemprop#233]
Heello, dear maintainers,
When I run `chemprop_train` providing `--atom_descriptors_path`, I get an error if I provide `.npz` file where atom descriptors are `np.array` (one array per molecule) of shape _(1,number_of_atoms)_. But I dont get error when the shape is _(number_of_atoms,1)_. So, I would go for the second version. However, when I run  `chemprop_fingerprint` with this second version, I get another error. **_So my question is: what is the correct format to use?_**

**Examples:**

Model trained with atom_descriptors of shape  _(number_of_atoms,1)_:
`chemprop_fingerprint --checkpoint_path bace_reg_descriptors/fold_0/model_0/model.pt --atom_descriptors_path ../descriptors/train.npz --atom_descriptors  descriptor --test_path ../data/bace_reg_train.csv --preds_path preds`
Error:
```
Traceback (most recent call last):
  File "/home/maria/anaconda2/envs/chemprop/bin/chemprop_fingerprint", line 33, in <module>
    sys.exit(load_entry_point('chemprop', 'console_scripts', 'chemprop_fingerprint')())
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/train/molecule_fingerprint.py", line 189, in chemprop_fingerprint
    molecule_fingerprint(args=FingerprintArgs().parse_args())
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/utils.py", line 574, in wrap
    result = func(*args, **kwargs)
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/train/molecule_fingerprint.py", line 116, in molecule_fingerprint
    all_fingerprints[:,:,index] = model_fp
ValueError: could not broadcast input array from shape (1065,301) into shape (1065,300)
```

Model trained with atom_descriptors of shape  _(number_of_atoms,1)_ , only difference now we use `--descriptor feature` command line argument:
```
chemprop_fingerprint --checkpoint_path bace_reg_features/fold_0/model_0/model.pt --atom_descriptors_path ../descriptors/train.npz --atom_descriptors feature --test_path ../data/bace_reg_train.csv --preds_path pred
```
Error:
```
Traceback (most recent call last):
  File "/home/maria/anaconda2/envs/chemprop/bin/chemprop_fingerprint", line 33, in <module>
    sys.exit(load_entry_point('chemprop', 'console_scripts', 'chemprop_fingerprint')())
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/train/molecule_fingerprint.py", line 189, in chemprop_fingerprint
    molecule_fingerprint(args=FingerprintArgs().parse_args())
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/utils.py", line 574, in wrap
    result = func(*args, **kwargs)
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/train/molecule_fingerprint.py", line 109, in molecule_fingerprint
    model_fp = model_fingerprint(
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/train/molecule_fingerprint.py", line 166, in model_fingerprint
    for batch in tqdm(data_loader, disable=disable_progress_bar, leave=False):
  File "/home/maria/anaconda2/envs/chemprop/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/maria/anaconda2/envs/chemprop/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/maria/anaconda2/envs/chemprop/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/maria/anaconda2/envs/chemprop/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/maria/anaconda2/envs/chemprop/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/maria/anaconda2/envs/chemprop/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/maria/anaconda2/envs/chemprop/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/data/data.py", line 604, in construct_molecule_batch
    data.batch_graph()  # Forces computation and caching of the BatchMolGraph for the molecules
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/data/data.py", line 311, in batch_graph
    self._batch_graph = [BatchMolGraph([g[i] for g in mol_graphs]) for i in range(len(mol_graphs[0]))]
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/data/data.py", line 311, in <listcomp>
    self._batch_graph = [BatchMolGraph([g[i] for g in mol_graphs]) for i in range(len(mol_graphs[0]))]
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/features/featurization.py", line 526, in __init__
    self.f_atoms = torch.FloatTensor(f_atoms)
ValueError: expected sequence of length 133 at dim 1 (got 134)
```
Model _training_ with descriptors of shape _(1, number_of_atoms)_:
` chemprop_train --data_path ../data/bace_reg_train.csv --dataset_type regression --save_dir bace_reg_descriptors/ --atom_descriptors_path ../descriptors/train_expand.npz --atom_descriptors descriptor`
Error:
```
Traceback (most recent call last):
  File "/home/maria/anaconda2/envs/chemprop/bin/chemprop_train", line 33, in <module>
    sys.exit(load_entry_point('chemprop', 'console_scripts', 'chemprop_train')())
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/train/cross_validate.py", line 190, in chemprop_train
    cross_validate(args=TrainArgs().parse_args(), train_func=run_training)
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/utils.py", line 574, in wrap
    result = func(*args, **kwargs)
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/train/cross_validate.py", line 113, in cross_validate
    model_scores = train_func(args, data, logger)
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/train/run_training.py", line 123, in run_training
    atom_descriptor_scaler = train_data.normalize_features(replace_nan_token=0, scale_atom_descriptors=True)
  File "/mnt/d/privatecloud/affinity_ai/chemprop/chemprop/data/data.py", line 458, in normalize_features
    features = np.vstack([d.raw_atom_descriptors for d in self._data])
  File "<__array_function__ internals>", line 180, in vstack
  File "/home/maria/anaconda2/envs/chemprop/lib/python3.8/site-packages/numpy/core/shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 31 and the array at index 1 has size 30
```
(BTW, reading descriptors has issues when reading from pandas, but that's better to open  another issue.)

**Comment by cjmcgill** [comment]
@MariBerry it looks like you have gotten to the bottom of this already, but the right format is shape(num_atoms, num_features) for atoms or shape(num_bonds, num_features) for bonds.

There is a pending change to loading pandas from pkl files in #226 that may address what you're seeing while trying to solve a different problem. The two expected pandas formats are `{"feature_name":shape(num_molecules, num_atoms)}` or `{"feature_group_name":shape(num_molecules, num_atoms, num_features)}`. If one of these formats is doing something unexpected, please do open another issue so we can fix it.
