### ISSUE TITLE
Training works but hyperparameter optimization gives errors

### ISSUE THREAD

**Issue by Evert-Homan** [chemprop/chemprop#243]
Hi,

Using the tox21 data set and following the tutorial, training a classification model works fine but when attempting a hyperparameter optimization I get a number of Python-related errors. The list of packages in the environement are further down if this is helpful.

Please advise. Thank you/Evert

chemprop_hyperopt --data_path data/tox21.csv --dataset_type classification --num_iters 5 --config_save_path tox21_hyperopt
WARNING:root:No normalization for BCUT2D_MWHI
WARNING:root:No normalization for BCUT2D_MWLOW
WARNING:root:No normalization for BCUT2D_CHGHI
WARNING:root:No normalization for BCUT2D_CHGLO
WARNING:root:No normalization for BCUT2D_LOGPHI
WARNING:root:No normalization for BCUT2D_LOGPLOW
WARNING:root:No normalization for BCUT2D_MRHI
WARNING:root:No normalization for BCUT2D_MRLOW
No manual trials loaded as part of hyperparameter search
Initiating trial with seed 0
Loaded 0 previous trials
Parameters assigned with random search, 10 random trials remaining
  0%|                                     | 0/1 [00:00<?, ?trial/s, best loss=?]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/chemprop/bin/chemprop_hyperopt", line 8, in <module>
    sys.exit(chemprop_hyperopt())
  File "/opt/anaconda3/envs/chemprop/lib/python3.8/site-packages/chemprop/hyperparameter_optimization.py", line 164, in chemprop_hyperopt
    hyperopt(args=HyperoptArgs().parse_args())
  File "/opt/anaconda3/envs/chemprop/lib/python3.8/site-packages/chemprop/utils.py", line 574, in wrap
    result = func(*args, **kwargs)
  File "/opt/anaconda3/envs/chemprop/lib/python3.8/site-packages/chemprop/hyperparameter_optimization.py", line 129, in hyperopt
    fmin(
  File "/opt/anaconda3/envs/chemprop/lib/python3.8/site-packages/hyperopt/fmin.py", line 540, in fmin
    return trials.fmin(
  File "/opt/anaconda3/envs/chemprop/lib/python3.8/site-packages/hyperopt/base.py", line 671, in fmin
    return fmin(
  File "/opt/anaconda3/envs/chemprop/lib/python3.8/site-packages/hyperopt/fmin.py", line 586, in fmin
    rval.exhaust()
  File "/opt/anaconda3/envs/chemprop/lib/python3.8/site-packages/hyperopt/fmin.py", line 364, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/opt/anaconda3/envs/chemprop/lib/python3.8/site-packages/hyperopt/fmin.py", line 279, in run
    new_ids, self.domain, trials, self.rstate.integers(2 ** 31 - 1)
AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'

conda list
# packages in environment at /opt/anaconda3/envs/chemprop:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
alabaster                 0.7.12                   pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
blas                      1.0                         mkl  
boost                     1.74.0           py38hc10631b_3    conda-forge
boost-cpp                 1.74.0               h9359b55_0    conda-forge
brotlipy                  0.7.0           py38h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.10.8            ha878542_0    conda-forge
cairo                     1.16.0               hf32fb01_1  
certifi                   2021.10.8        py38h578d9bd_1    conda-forge
cffi                      1.15.0           py38hd667e15_1  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
chemprop                  1.4.1                    pypi_0    pypi
click                     8.0.3                    pypi_0    pypi
cloudpickle               2.0.0                    pypi_0    pypi
cryptography              36.0.0           py38h9ce1e76_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
cudnn                     8.2.1                cuda11.3_0  
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
descriptastorus           2.3.0.5                  pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
ffmpeg                    4.2.2                h20bf706_0  
flask                     2.0.2                    pypi_0    pypi
fontconfig                2.13.1               h6c09931_0  
freetype                  2.11.0               h70c0345_0  
future                    0.18.2                   pypi_0    pypi
giflib                    5.2.1                h7b6447c_0  
glib                      2.69.1               h4ff587b_1  
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
gunicorn                  20.1.0                   pypi_0    pypi
hyperopt                  0.2.7                    pypi_0    pypi
icu                       67.1                 he1b5a44_0    conda-forge
idna                      3.3                pyhd3eb1b0_0  
imagesize                 1.3.0                    pypi_0    pypi
importlib-metadata        4.10.1                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
itsdangerous              2.0.1                    pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9d                   h7f8727e_0  
kiwisolver                1.3.1            py38h2531618_0  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libiconv                  1.16                 h516909a_0    conda-forge
libidn2                   2.3.2                h7f8727e_0  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.2.0                h85742a9_0  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.0.3                h7f8727e_2  
libuv                     1.40.0               h7b6447c_0  
libvpx                    1.7.0                h439df22_0  
libwebp                   1.2.0                h89dd481_0  
libwebp-base              1.2.0                h27cfd23_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               h68273f3_2    conda-forge
lz4-c                     1.9.3                h295c915_1  
markupsafe                2.0.1                    pypi_0    pypi
matplotlib-base           3.3.4            py38h0efea84_0    conda-forge
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py38h7f8727e_0  
mkl_fft                   1.3.1            py38hd3c417c_0  
mkl_random                1.2.2            py38h51133e4_0  
mypy-extensions           0.4.3                    pypi_0    pypi
ncurses                   6.3                  h7f8727e_2  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.6.3                    pypi_0    pypi
numpy                     1.21.2           py38h20f2e39_0  
numpy-base                1.21.2           py38h79a1101_0  
olefile                   0.46               pyhd3eb1b0_0  
openh264                  2.1.1                h4ff587b_0  
openssl                   1.1.1m               h7f8727e_0  
packaging                 21.3                     pypi_0    pypi
pandas                    1.2.3            py38h51da96c_0    conda-forge
pandas-flavor             0.2.0                    pypi_0    pypi
pcre                      8.45                 h9c3ff4c_0    conda-forge
pillow                    8.4.0            py38h5aabda8_0  
pip                       21.2.4           py38h06a4308_0  
pixman                    0.40.0               h36c2ea0_0    conda-forge
protobuf                  3.19.4                   pypi_0    pypi
py4j                      0.10.9.3                 pypi_0    pypi
pycairo                   1.20.1           py38hf61ee4a_0    conda-forge
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.11.2                   pypi_0    pypi
pyopenssl                 21.0.0             pyhd3eb1b0_1  
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.12               h12debd9_0  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.11.0.dev20220130 py3.8_cuda11.3_cudnn8.2.0_0    pytorch-nightly
pytorch-mutex             1.0                        cuda    pytorch-nightly
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
rdkit                     2020.09.5        py38h2bca085_0    conda-forge
readline                  8.1.2                h7f8727e_1  
reportlab                 3.5.68           py38hadf75a6_0    conda-forge
requests                  2.27.1             pyhd3eb1b0_0  
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
setuptools                58.0.4           py38h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    4.4.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlalchemy                1.3.23           py38h497a2fe_0    conda-forge
sqlite                    3.37.0               hc218d9a_0  
tensorboardx              2.4.1                    pypi_0    pypi
threadpoolctl             3.0.0                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_0  
torchaudio                0.11.0.dev20220130      py38_cu113    pytorch-nightly
torchvision               0.12.0.dev20220130      py38_cu113    pytorch-nightly
tornado                   6.1              py38h497a2fe_1    conda-forge
tqdm                      4.62.3                   pypi_0    pypi
typed-argument-parser     1.7.2                    pypi_0    pypi
typing-inspect            0.7.1                    pypi_0    pypi
typing_extensions         3.10.0.2           pyh06a4308_0  
urllib3                   1.26.7             pyhd3eb1b0_0  
werkzeug                  2.0.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
x264                      1!157.20191217       h7b6447c_0  
xarray                    0.21.0                   pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
zipp                      3.7.0                    pypi_0    pypi
zlib                      1.2.11               h7f8727e_4  
zstd                      1.4.9                haebb681_0

**Comment by cjmcgill** [comment]
Thanks for sharing your environment list. The error here is a change in how the newest version of hyperopt (0.2.7) handles a the deprecation of an old way of numpy generating random numbers, which was passed in to hyperopt as an input. Both ways were still allowed by numpy, but in 0.2.7 hyperopt switched to supporting the new one internally.

Thanks for pointing this out. I'll look at a bug fix.

**Comment by Evert-Homan** [comment]
Hi Charles,

After updating the environment I can confirm that hyperparameter optimization now works.

Thanks for your support/Evert

**Comment by cjmcgill** [comment]
Glad this solution works for you and thanks for letting us know about the problem before it affected more and more users.
