### ISSUE TITLE
[BUG]: chemprop_hyperopt directory issue

### ISSUE THREAD

**Issue by jessegmeyerlab** [chemprop/chemprop#254]
Thanks for building this awesome package!!! Easily the best option for modern learning from chemical structure. '

**Describe the bug**
Seems to be a temporary directory issue when I try to run chemprop_hyperopt 

**Example(s)**
```
(chemprop) C:\Users\jesmeyer\OneDrive - mcw.edu\Documents\GitHub\LincsReg>chemprop_hyperopt --data_path data/VCAP_24h_10uM_train_classes.csv --dataset_type multiclass --num_iters 100 --config_save_path chemprop
WARNING:root:No normalization for BCUT2D_MWHI
WARNING:root:No normalization for BCUT2D_MWLOW
WARNING:root:No normalization for BCUT2D_CHGHI
WARNING:root:No normalization for BCUT2D_CHGLO
WARNING:root:No normalization for BCUT2D_LOGPHI
WARNING:root:No normalization for BCUT2D_LOGPLOW
WARNING:root:No normalization for BCUT2D_MRHI
WARNING:root:No normalization for BCUT2D_MRLOW
No manual trials loaded as part of hyperparameter search
Initiating trial with seed 0
Loaded 0 previous trials
Parameters assigned with random search, 10 random trials remaining
  0%|                                                                            | 0/1 [00:00<?, ?trial/s, best loss=?]
Traceback (most recent call last):
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jesmeyer\.conda\envs\chemprop\Scripts\chemprop_hyperopt.exe\__main__.py", line 7, in <module>
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\site-packages\chemprop\hyperparameter_optimization.py", line 164, in chemprop_hyperopt
    hyperopt(args=HyperoptArgs().parse_args())
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\site-packages\chemprop\utils.py", line 574, in wrap
    result = func(*args, **kwargs)
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\site-packages\chemprop\hyperparameter_optimization.py", line 129, in hyperopt
    fmin(
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\site-packages\hyperopt\fmin.py", line 540, in fmin
    return trials.fmin(
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\site-packages\hyperopt\base.py", line 671, in fmin
    return fmin(
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\site-packages\hyperopt\fmin.py", line 586, in fmin
    rval.exhaust()
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\site-packages\hyperopt\fmin.py", line 364, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\site-packages\hyperopt\fmin.py", line 279, in run
    new_ids, self.domain, trials, self.rstate.integers(2 ** 31 - 1)
AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'
Traceback (most recent call last):
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\jesmeyer\\AppData\\Local\\Temp\\tmpe3635c9g\\quiet.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\tempfile.py", line 802, in onerror
    _os.unlink(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\jesmeyer\\AppData\\Local\\Temp\\tmpe3635c9g\\quiet.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\weakref.py", line 642, in _exitfunc
    f()
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\tempfile.py", line 817, in _cleanup
    cls._rmtree(name)
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\tempfile.py", line 813, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\tempfile.py", line 805, in onerror
    cls._rmtree(path)
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\tempfile.py", line 813, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\shutil.py", line 599, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\jesmeyer\.conda\envs\chemprop\lib\shutil.py", line 596, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\jesmeyer\\AppData\\Local\\Temp\\tmpe3635c9g\\quiet.log'

(chemprop) C:\Users\jesmeyer\OneDrive - mcw.edu\Documents\GitHub\LincsReg>
```

**Expected behavior**
It should run hyperopt.

**Environment**
- python version = 3.8
- package versions: `conda list` or `pip list`
```
(chemprop) C:\Users\jesmeyer\OneDrive - mcw.edu\Documents\GitHub\LincsReg>conda list
# packages in environment at C:\Users\jesmeyer\.conda\envs\chemprop:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
boost                     1.74.0           py38he5193b3_5    conda-forge
boost-cpp                 1.74.0               h9f4b32c_7    conda-forge
brotli                    1.0.9                h8ffe710_6    conda-forge
brotli-bin                1.0.9                h8ffe710_6    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
cairo                     1.16.0            h15b3021_1009    conda-forge
certifi                   2021.10.8        py38haa244fe_1    conda-forge
charset-normalizer        2.0.12                   pypi_0    pypi
chemprop                  1.4.1                    pypi_0    pypi
click                     8.0.4                    pypi_0    pypi
cloudpickle               2.0.0                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
descriptastorus           2.3.0.5                  pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
flask                     2.0.3                    pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.96              h1989441_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.29.1           py38h294d835_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
future                    0.18.2                   pypi_0    pypi
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
greenlet                  1.1.2            py38h885f38d_1    conda-forge
hyperopt                  0.2.7                    pypi_0    pypi
icu                       69.1                 h0e60522_0    conda-forge
idna                      3.3                      pypi_0    pypi
imagesize                 1.3.0                    pypi_0    pypi
importlib-metadata        4.11.2                   pypi_0    pypi
intel-openmp              2022.0.0          h57928b3_3663    conda-forge
itsdangerous              2.1.0                    pypi_0    pypi
jbig                      2.1               h8d14728_2003    conda-forge
jinja2                    3.0.3                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h8ffe710_0    conda-forge
kiwisolver                1.3.2            py38hbd9d945_1    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              13_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_6    conda-forge
libbrotlidec              1.0.9                h8ffe710_6    conda-forge
libbrotlienc              1.0.9                h8ffe710_6    conda-forge
libcblas                  3.9.0              13_win64_mkl    conda-forge
libdeflate                1.10                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.70.2               h3be07f2_4    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              13_win64_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libtiff                   4.3.0                hc4061b1_3    conda-forge
libwebp                   1.2.2                h57928b3_0    conda-forge
libwebp-base              1.2.2                h8ffe710_1    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.12               hf5bbc77_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.1.0                    pypi_0    pypi
matplotlib-base           3.5.1            py38h1f000d6_0    conda-forge
mkl                       2022.0.0           h0e2418a_796    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy-extensions           0.4.3                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
numpy                     1.22.2           py38hcf66579_0    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   3.0.0                h8ffe710_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.1            py38h5d928e2_0    conda-forge
pandas-flavor             0.2.0                    pypi_0    pypi
pcre                      8.45                 h0e60522_0    conda-forge
pillow                    9.0.1            py38hd8e0db4_2    conda-forge
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
protobuf                  3.19.4                   pypi_0    pypi
pthread-stubs             0.4               hcd874cb_1001    conda-forge
py4j                      0.10.9.3                 pypi_0    pypi
pycairo                   1.20.1           py38h979ce04_1    conda-forge
pygments                  2.11.2                   pypi_0    pypi
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
python                    3.8.12          h900ac77_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
rdkit                     2021.09.4        py38h6643f78_0    conda-forge
reportlab                 3.5.68           py38hc3ca807_1    conda-forge
requests                  2.27.1                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.8.0                    pypi_0    pypi
setuptools                60.9.3           py38haa244fe_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    4.4.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlalchemy                1.4.31           py38h294d835_0    conda-forge
sqlite                    3.37.0               h8ffe710_0    conda-forge
tbb                       2021.5.0             h2d74725_0    conda-forge
tensorboardx              2.5                      pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
torch                     1.10.2+cu102             pypi_0    pypi
torchaudio                0.10.2+cu102             pypi_0    pypi
torchvision               0.11.3+cu102             pypi_0    pypi
tqdm                      4.63.0                   pypi_0    pypi
typed-argument-parser     1.7.2                    pypi_0    pypi
typing-extensions         4.1.1                    pypi_0    pypi
typing-inspect            0.7.1                    pypi_0    pypi
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py38h294d835_0    conda-forge
urllib3                   1.26.8                   pypi_0    pypi
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xarray                    0.21.1                   pypi_0    pypi
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zipp                      3.7.0                    pypi_0    pypi
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.2                h6255e5f_0    conda-forge
```
- OS - windows 10 enterprise

**Checklist**
- [x] all dependencies are satisifed: `conda list` shows the packages listed in the `README`
- [ ] the unit tests are working: `pytest -v` reports no errors

**Additional context**
Maybe related to trying multiclass optimization?

**Comment by jessegmeyerlab** [comment]
I can confirm that it also fails when trying regression, so its not specific to multiclassification

**Comment by davidegraff** [comment]
looks like it's actually an `AttributeError` from the stacktrace:

`AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'`

but this is odd because looking at the code of the [`fmin()` function](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/fmin.py#L369) inside `hyperopt` and following the stack trace,  `self.rstate` has two possibilities, both of which return a numpy `Generator` object. I've looked at your environment and you have the latest version of `numpy`, which would cause that object to **support** the `integers()` method.

All of this is to say that I'm confused, because the stacktrace only contains standard library functions, and I doubt those are those source of errors

**Comment by mliu49** [comment]
I think this is the same error as #243, which was introduced by a recent change in hyperopt. It was fixed in #245, so you should be able to fix it by updating chemprop.

**Comment by cjmcgill** [comment]
@jessegmeyerlab can you confirm whether you have an updated version of chemprop after #245?

**Comment by cjmcgill** [comment]
@jessegmeyerlab I'm closing this because I think your issue has been addressed but please reopen this if you need more assistance.

**Comment by jessegmeyerlab** [comment]
Sorry for the late reply. We're moving my lab starting this week, so it
might be a month before I can revisit this.
