### ISSUE TITLE
[ERROR] subprocess.CalledProcessError: Command '['git', 'remote', 'get-url', 'origin']' returned non-zero exit status 129.

### ISSUE THREAD

**Issue by nathanmlim** [chemprop/chemprop#28]
I am getting some error related to `git` with the latest changes to the master branch. Full trace back below

```
(chemprop) nlim@u18:~/Github/chemprop$ python train.py --data_path data/tox21.csv --dataset_type classification --save_dir tox21_checkpoints
Fold 0
Command line
python train.py --data_path data/tox21.csv --dataset_type classification --save_dir tox21_checkpoints
Args
{'activation': 'ReLU',
 'atom_messages': False,
 'batch_size': 50,
 'bias': False,
 'cache_cutoff': 10000,
 'checkpoint_dir': None,
 'checkpoint_path': None,
 'checkpoint_paths': None,
 'class_balance': False,
 'config_path': None,
 'crossval_index_dir': None,
 'crossval_index_file': None,
 'crossval_index_sets': None,
 'cuda': True,
 'data_path': 'data/tox21.csv',
 'dataset_type': 'classification',
 'depth': 3,
 'device': device(type='cuda'),
 'dropout': 0.0,
 'ensemble_size': 1,
 'epochs': 30,
 'features_generator': None,
 'features_only': False,
 'features_path': None,
 'features_scaling': True,
 'features_size': None,
 'ffn_hidden_size': 300,
 'ffn_num_layers': 2,
 'final_lr': 0.0001,
 'folds_file': None,
 'gpu': None,
 'hidden_size': 300,
 'init_lr': 0.0001,
 'log_frequency': 10,
 'max_data_size': None,
 'max_lr': 0.001,
 'metric': 'auc',
 'minimize_score': False,
 'multiclass_num_classes': 3,
 'no_cuda': False,
 'no_features_scaling': False,
 'num_folds': 1,
 'num_lrs': 1,
 'num_tasks': None,
 'num_workers': 4,
 'output_size': None,
 'pytorch_seed': 0,
 'quiet': False,
 'save_dir': 'tox21_checkpoints/fold_0',
 'save_smiles_splits': False,
 'seed': 0,
 'separate_test_features_path': None,
 'separate_test_path': None,
 'separate_val_features_path': None,
 'separate_val_path': None,
 'show_individual_scores': False,
 'smiles_column': None,
 'split_sizes': (0.8, 0.1, 0.1),
 'split_type': 'random',
 'target_columns': None,
 'task_names': None,
 'test': False,
 'test_fold_index': None,
 'train_data_size': None,
 'undirected': False,
 'use_input_features': False,
 'val_fold_index': None,
 'warmup_epochs': 2.0}
error: Unknown subcommand: get-url
usage: git remote [-v | --verbose]
   or: git remote add [-t <branch>] [-m <master>] [-f] [--tags|--no-tags] [--mirror=<fetch|push>] <name> <url>
   or: git remote rename <old> <new>
   or: git remote remove <name>
   or: git remote set-head <name> (-a | -d | <branch>)
   or: git remote [-v | --verbose] show [-n] <name>
   or: git remote prune [-n | --dry-run] <name>
   or: git remote [-v | --verbose] update [-p | --prune] [(<group> | <remote>)...]
   or: git remote set-branches [--add] <name> <branch>...
   or: git remote set-url [--push] <name> <newurl> [<oldurl>]
   or: git remote set-url --add <name> <newurl>
   or: git remote set-url --delete <name> <url>

    -v, --verbose         be verbose; must be placed before a subcommand

Traceback (most recent call last):
  File "train.py", line 11, in <module>
    cross_validate(args, logger)
  File "/data/nlim/Github/chemprop/chemprop/train/cross_validate.py", line 29, in cross_validate
    model_scores = run_training(args, logger)
  File "/data/nlim/Github/chemprop/chemprop/train/run_training.py", line 48, in run_training
    args.save(os.path.join(args.save_dir, 'args.json'))
  File "/data/nlim/anaconda3/envs/chemprop/lib/python3.7/site-packages/tap/tap.py", line 445, in save
    json.dump(self._log_all(), f, indent=4, sort_keys=True, cls=PythonObjectEncoder)
  File "/data/nlim/anaconda3/envs/chemprop/lib/python3.7/site-packages/tap/tap.py", line 277, in _log_all
    arg_log['reproducibility'] = self.get_reproducibility_info()
  File "/data/nlim/anaconda3/envs/chemprop/lib/python3.7/site-packages/tap/tap.py", line 266, in get_reproducibility_info
    reproducibility['git_url'] = get_git_url(commit_hash=True)
  File "/data/nlim/anaconda3/envs/chemprop/lib/python3.7/site-packages/tap/utils.py", line 61, in get_git_url
    url = check_output(['git', 'remote', 'get-url', 'origin'])
  File "/data/nlim/anaconda3/envs/chemprop/lib/python3.7/site-packages/tap/utils.py", line 30, in check_output
    return subprocess.check_output(command).decode('utf-8').strip()
  File "/data/nlim/anaconda3/envs/chemprop/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/data/nlim/anaconda3/envs/chemprop/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'remote', 'get-url', 'origin']' returned non-zero exit status 129.
``

**Comment by nathanmlim** [comment]
Oops, updating to git 2.23.0 solved this problem.

**Comment by nathanmlim** [comment]
Re-opening. I can run the example datasets but when I use my own datasets I get a new but similar error:

```
python /data/nlim/Github/chemprop/train.py --data_path /data/nlim/Projects//hitlist-clean.csv --save_dir full_checkpoints --dataset_type regression --smiles_column SMILES --target_columns Score --num_workers 48 --gpu 0 --batch_size 5000
Args
{'activation': 'ReLU',
 'atom_messages': False,
 'batch_size': 5000,
 'bias': False,
 'cache_cutoff': 10000,
 'checkpoint_dir': None,
 'checkpoint_path': None,
 'checkpoint_paths': None,
 'class_balance': False,
 'config_path': None,
 'crossval_index_dir': None,
 'crossval_index_file': None,
 'crossval_index_sets': None,
 'cuda': True,
 'data_path': '/data/nlim/Projects/hitlist-clean.csv',
 'dataset_type': 'regression',
 'depth': 3,
 'device': device(type='cuda', index=0),
 'dropout': 0.0,
 'ensemble_size': 1,
 'epochs': 30,
 'features_generator': None,
 'features_only': False,
 'features_path': None,
 'features_scaling': True,
 'features_size': None,
 'ffn_hidden_size': 300,
 'ffn_num_layers': 2,
 'final_lr': 0.0001,
 'folds_file': None,
 'gpu': 0,
 'hidden_size': 300,
 'init_lr': 0.0001,
 'log_frequency': 10,
 'max_data_size': None,
 'max_lr': 0.001,
 'metric': 'rmse',
 'minimize_score': True,
 'multiclass_num_classes': 3,
 'no_cuda': False,
 'no_features_scaling': False,
 'num_folds': 1,
 'num_lrs': 1,
 'num_tasks': None,
 'num_workers': 48,
 'output_size': None,
 'pytorch_seed': 0,
 'quiet': False,
 'save_dir': 'full_checkpoints/fold_0',
 'save_smiles_splits': False,
 'seed': 0,
 'separate_test_features_path': None,
 'separate_test_path': None,
 'separate_val_features_path': None,
 'separate_val_path': None,
 'show_individual_scores': False,
 'smiles_column': 'SMILES',
 'split_sizes': (0.8, 0.1, 0.1),
 'split_type': 'random',
 'target_columns': ['Score'],
 'task_names': None,
 'test': False,
 'test_fold_index': None,
 'train_data_size': None,
 'undirected': False,
 'use_input_features': False,
 'val_fold_index': None,
 'warmup_epochs': 2.0}
fatal: not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "/data/nlim/Github/chemprop/train.py", line 11, in <module>
    cross_validate(args, logger)
  File "/data/nlim/Github/chemprop/chemprop/train/cross_validate.py", line 29, in cross_validate
    model_scores = run_training(args, logger)
  File "/data/nlim/Github/chemprop/chemprop/train/run_training.py", line 48, in run_training
    args.save(os.path.join(args.save_dir, 'args.json'))
  File "/data/nlim/Github/typed-argument-parser/tap/tap.py", line 445, in save
    json.dump(self._log_all(), f, indent=4, sort_keys=True, cls=PythonObjectEncoder)
  File "/data/nlim/Github/typed-argument-parser/tap/tap.py", line 277, in _log_all
    arg_log['reproducibility'] = self.get_reproducibility_info()
  File "/data/nlim/Github/typed-argument-parser/tap/tap.py", line 265, in get_reproducibility_info
    reproducibility['git_root'] = get_git_root()
  File "/data/nlim/Github/typed-argument-parser/tap/utils.py", line 50, in get_git_root
    return check_output(['git', 'rev-parse', '--show-toplevel'])
  File "/data/nlim/Github/typed-argument-parser/tap/utils.py", line 30, in check_output
    return subprocess.check_output(command).decode('utf-8').strip()
  File "/data/nlim/anaconda3/envs/chemprop/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/data/nlim/anaconda3/envs/chemprop/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--show-toplevel']' returned non-zero exit status 128.
```

**Comment by nathanmlim** [comment]
Figured out the issue. I have to call train.py from the github repo directory. I get the above error when trying to execute `train.py` in any other directory.

**Comment by JamesALumley** [comment]
This problem persists for me even when I run the code from the install directory.  There is a simple work around, commenting out line 46 from /hpc/scratch/userid/builds/chemprop/chemprop/train/run_training.py

 41     # Print args
 42     debug('Args')
 43     debug(args)
 44
 45     # Save args ****Comment this out****
 46     #args.save(os.path.join(args.save_dir, 'args.json'))
 47
 48     # Set pytorch seed for random initial weights
 49     torch.manual_seed(args.pytorch_seed)
 50

running the git config command within the install dir does return the repo correctly.
userid@login chemprop]$ git config --get remote.origin.url
https://github.com/chemprop/chemprop.git

Typically, you would not run the code from in the directory it's install and would run from a separate model build directory so seems like a fix is needed?

Full trace below:

Traceback (most recent call last):
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/site-packages/tap/utils.py", line 66, in get_git_url
    url = check_output(['git', 'remote', 'get-url', 'origin'])
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/site-packages/tap/utils.py", line 33, in check_output
    output = subprocess.check_output(command, stderr=devnull).decode('utf-8').strip()
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'remote', 'get-url', 'origin']' returned non-zero exit status 129.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 7, in <module>
    chemprop_train()
  File "/hpc/scratch/userid/builds/chemprop/chemprop/utils.py", line 376, in wrap
    result = func(*args, **kwargs)
  File "/hpc/scratch/userid/builds/chemprop/chemprop/train/cross_validate.py", line 95, in chemprop_train
    cross_validate(args=args, logger=logger)
  File "/hpc/scratch/userid/builds/chemprop/chemprop/train/cross_validate.py", line 48, in cross_validate
    model_scores = run_training(args, logger)
  File "/hpc/scratch/userid/builds/chemprop/chemprop/train/run_training.py", line 47, in run_training
    args.save(os.path.join(args.save_dir, 'args.json'))
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/site-packages/tap/tap.py", line 501, in save
    args = self._log_all() if with_reproducibility else self.as_dict()
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/site-packages/tap/tap.py", line 292, in _log_all
    arg_log['reproducibility'] = self.get_reproducibility_info()
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/site-packages/tap/tap.py", line 281, in get_reproducibility_info
    reproducibility['git_url'] = get_git_url(commit_hash=True)
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/site-packages/tap/utils.py", line 69, in get_git_url
    url = check_output(['git' 'config' '--get' 'remote.origin.url'])
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/site-packages/tap/utils.py", line 33, in check_output
    output = subprocess.check_output(command, stderr=devnull).decode('utf-8').strip()
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/userid/.conda/envs/my-rdkit-env/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gitconfig--getremote.origin.url': 'gitconfig--getremote.origin.url'
(my-rdkit-env) [userid@login1 chemprop]$
