### ISSUE TITLE
[BUG]: Calibrated predictions on multi-task setup are failing

### ISSUE THREAD

**Issue by muammar** [chemprop/chemprop#292]
**Describe the bug**
If you train a model for a multi-task regression case using the flag `--loss_function evidential`, and then you try to make predictions with calibrated uncertainties with the following flags: 

```
--uncertainty_method evidential_epistemic 
--calibration_method scaling 
--regression_calibrator_metric stdev 
--calibration_path PATH_TO_CALIBRATION_SET
```

Then, `chemprop_predict` fails in the following line: 

```
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".
Moving model to cuda
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.84s/it]
Traceback (most recent call last):                                                                                                                                                  
  File "/home/muammar/miniconda3/envs/py39/bin/chemprop_predict", line 8, in <module>
    sys.exit(chemprop_predict())
  File "/home/muammar/miniconda3/envs/py39/lib/python3.9/site-packages/chemprop/train/make_predictions.py", line 497, in chemprop_predict
    make_predictions(args=PredictArgs().parse_args())
  File "/home/muammar/miniconda3/envs/py39/lib/python3.9/site-packages/chemprop/utils.py", line 538, in wrap
    result = func(*args, **kwargs)
  File "/home/muammar/miniconda3/envs/py39/lib/python3.9/site-packages/chemprop/train/make_predictions.py", line 431, in make_predictions
    calibrator = build_uncertainty_calibrator(
  File "/home/muammar/miniconda3/envs/py39/lib/python3.9/site-packages/chemprop/uncertainty/uncertainty_calibrator.py", line 722, in build_uncertainty_calibrator
    calibrator = calibrator_class(
  File "/home/muammar/miniconda3/envs/py39/lib/python3.9/site-packages/chemprop/uncertainty/uncertainty_calibrator.py", line 68, in __init__
    self.calibrate()
  File "/home/muammar/miniconda3/envs/py39/lib/python3.9/site-packages/chemprop/uncertainty/uncertainty_calibrator.py", line 151, in calibrate
    errors = uncal_preds - targets
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

Adding a `print(targets)` statement before the line with the error reveals that my calibration set has some `None` values. 

```
[3.1654750481410856 None]
 [3.202746442938317 None]]
```
For now, I will just discard all rows for which at least one of the tasks is `None`. 

**Example(s)**
Train an MTL model with the `evidential` loss, and use a multi-task calibration set with `None` values. 

**Expected behavior**
Drop `None` values from the multi-task calibration data set and warn users. 

**Screenshots**

**Environment**
- python version: 3.9
- package versions: `conda list` or `pip list`
````
  % conda list                                                                                                                                                               !10214
# packages in environment at /home/muammar/miniconda3/envs/py39:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   0.15.0             pyhd3eb1b0_0  
aiohttp                   3.8.1            py39h7f8727e_1  
aiosignal                 1.2.0              pyhd3eb1b0_0  
alabaster                 0.7.12                   pypi_0    pypi
anyio                     3.5.0            py39h06a4308_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h7f8727e_0  
astroid                   2.9.0            py39h06a4308_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
async-timeout             4.0.1              pyhd3eb1b0_0  
attrs                     21.4.0             pyhd3eb1b0_0  
babel                     2.9.1              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.11.1           py39h06a4308_0  
black                     19.10b0                    py_0  
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
blinker                   1.4              py39h06a4308_0  
boost                     1.74.0           py39h5472131_5    conda-forge
boost-cpp                 1.74.0               h9359b55_0    conda-forge
bottleneck                1.3.4            py39hce1f21e_0  
brotli                    1.0.9                he6710b0_2  
brotlipy                  0.7.0           py39h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.18.1               h7f8727e_0  
ca-certificates           2022.4.26            h06a4308_0  
cachetools                4.2.2              pyhd3eb1b0_0  
cairo                     1.16.0               h19f5f5c_2  
certifi                   2022.5.18.1      py39h06a4308_0  
cffi                      1.15.0           py39hd667e15_1  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
chemprop                  1.5.1                    pypi_0    pypi
click                     8.0.4            py39h06a4308_0  
cloudpickle               2.1.0                    pypi_0    pypi
cryptography              37.0.1           py39h9ce1e76_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
cycler                    0.11.0             pyhd3eb1b0_0  
daal4py                   2021.5.0         py39h78b71dc_0  
dal                       2021.5.1           h06a4308_803  
dataclasses               0.8                pyh6d0b6a4_7  
debugpy                   1.5.1            py39h295c915_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
descriptastorus           2.3.0.6                  pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
entrypoints               0.4              py39h06a4308_0  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.4.8                h27087fc_0    conda-forge
ffmpeg                    4.2.2                h20bf706_0  
flask                     2.1.2                    pypi_0    pypi
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.11.0               h70c0345_0  
frozenlist                1.2.0            py39h7f8727e_0  
future                    0.18.2           py39h06a4308_1  
giflib                    5.2.1                h7b6447c_0  
glib                      2.69.1               h4ff587b_1  
gmp                       6.2.1                h295c915_3  
gnutls                    3.6.15               he1e5248_0  
google-auth               2.6.0              pyhd3eb1b0_0  
google-auth-oauthlib      0.4.1                      py_2  
greenlet                  1.1.1            py39h295c915_0  
grpcio                    1.42.0           py39hce63b2e_0  
hyperopt                  0.2.7                    pypi_0    pypi
icu                       67.1                 he1b5a44_0    conda-forge
idna                      3.3                pyhd3eb1b0_0  
imagesize                 1.3.0                    pypi_0    pypi
importlib-metadata        4.11.3           py39h06a4308_0  
intel-openmp              2021.4.0          h06a4308_3561  
ipykernel                 6.9.1            py39h06a4308_0  
ipython                   8.3.0            py39h06a4308_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5              pyhd3eb1b0_1  
isort                     5.9.3              pyhd3eb1b0_0  
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.18.1           py39h06a4308_1  
jinja2                    3.0.3              pyhd3eb1b0_0  
joblib                    1.1.0              pyhd3eb1b0_0  
jpeg                      9e                   h7f8727e_0  
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                4.4.0            py39h06a4308_0  
jupyter_client            7.2.2            py39h06a4308_0  
jupyter_core              4.10.0           py39h06a4308_0  
jupyter_server            1.17.1           py39h06a4308_0  
jupyterlab                3.3.2              pyhd3eb1b0_0  
jupyterlab-code-formatter 1.4.11                   pypi_0    pypi
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.12.0           py39h06a4308_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
kiwisolver                1.4.2            py39h295c915_0  
lame                      3.100                h7b6447c_0  
lazy-loader               0.1rc2                   pypi_0    pypi
lazy-object-proxy         1.6.0            py39h27cfd23_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   11.2.0               h1234567_1  
libidn2                   2.3.2                h7f8727e_0  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.20.1               h4ff587b_0  
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.2.0                h85742a9_0  
libunistring              0.9.10               h27cfd23_0  
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.40.0               h7b6447c_0  
libvpx                    1.7.0                h439df22_0  
libwebp                   1.2.2                h55f646e_0  
libwebp-base              1.2.2                h7f8727e_0  
libxcb                    1.15                 h7f8727e_0  
lz4-c                     1.9.3                h295c915_1  
markdown                  3.3.4            py39h06a4308_0  
markupsafe                2.1.1            py39h7f8727e_0  
matplotlib-base           3.5.1            py39ha18d171_1  
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
mccabe                    0.7.0              pyhd3eb1b0_0  
mistune                   0.8.4           py39h27cfd23_1000  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
mpi                       1.0                       mpich  
mpich                     3.3.2                hc856adb_0  
msgpack-numpy             0.4.7.1            pyhd3eb1b0_0  
msgpack-python            1.0.3            py39hd09550d_0  
multidict                 5.2.0            py39h7f8727e_2  
munkres                   1.1.4                      py_0  
mypy_extensions           0.4.3            py39h06a4308_1  
nbclassic                 0.3.5              pyhd3eb1b0_0  
nbclient                  0.5.13           py39h06a4308_0  
nbconvert                 6.4.4            py39h06a4308_0  
nbformat                  5.3.0            py39h06a4308_0  
ncurses                   6.3                  h7f8727e_2  
nest-asyncio              1.5.5            py39h06a4308_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.8.2                    pypi_0    pypi
notebook                  6.4.11           py39h06a4308_0  
numexpr                   2.8.1            py39h6abb31d_0  
numpy                     1.22.3           py39he7a7128_0  
numpy-base                1.22.3           py39hf524024_0  
oauthlib                  3.2.0              pyhd8ed1ab_0    conda-forge
openh264                  2.1.1                h4ff587b_0  
openssl                   1.1.1o               h7f8727e_0  
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.4.2            py39h295c915_0  
pandas-flavor             0.3.0                    pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
pathspec                  0.7.0                      py_0  
patsy                     0.5.2            py39h06a4308_1  
pcre                      8.45                 h295c915_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.0.1            py39h22f2fdc_0  
pip                       21.2.4           py39h06a4308_0  
pixman                    0.40.0               h7f8727e_1  
platformdirs              2.4.0              pyhd3eb1b0_0  
plotly                    5.6.0              pyhd3eb1b0_0  
prometheus_client         0.13.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
protobuf                  3.20.1                   pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
py4j                      0.10.9.5                 pypi_0    pypi
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycairo                   1.19.1           py39h708ec4a_0  
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pyjwt                     2.4.0              pyhd8ed1ab_0    conda-forge
pylint                    2.12.2           py39h06a4308_1  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.4              pyhd3eb1b0_0  
pyrsistent                0.18.0           py39heee7806_0  
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.12               h12debd9_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.15.1             pyhd3eb1b0_0  
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.11.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-lightning         0.8.5                      py_0    conda-forge
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2022.1           py39h06a4308_0  
pyyaml                    6.0              py39h7f8727e_1  
pyzmq                     22.3.0           py39h295c915_2  
rdkit                     2022.03.2        py39h89e00b9_0    conda-forge
readline                  8.1.2                h7f8727e_1  
regex                     2022.3.15        py39h7f8727e_0  
reportlab                 3.5.67           py39hfdd840d_1  
requests                  2.27.1             pyhd3eb1b0_0  
requests-oauthlib         1.3.0                      py_0  
rsa                       4.7.2              pyhd3eb1b0_1  
scikit-learn              1.0.2            py39h51133e4_1  
scikit-learn-intelex      2021.5.0         py39h06a4308_0  
scipy                     1.7.3            py39hc147768_0  
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                61.2.0           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.2.0            py39h06a4308_1  
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.3.1              pyhd3eb1b0_0  
sphinx                    4.5.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlalchemy                1.4.32           py39h7f8727e_0  
sqlite                    3.38.3               hc218d9a_0  
stack_data                0.2.0              pyhd3eb1b0_0  
statsmodels               0.13.2           py39h7f8727e_0  
tbb                       2021.5.0             hd09550d_0  
tenacity                  8.0.1            py39h06a4308_0  
tensorboard               2.6.0                      py_1  
tensorboard-data-server   0.6.0            py39hca6d32c_0  
tensorboard-plugin-wit    1.6.0                      py_0  
tensorboardx              2.5                      pypi_0    pypi
terminado                 0.13.1           py39h06a4308_0  
testpath                  0.5.0              pyhd3eb1b0_0  
threadpoolctl             2.2.0              pyh0d69192_0  
tk                        8.6.12               h1ccaba5_0  
toml                      0.10.2             pyhd3eb1b0_0  
torchaudio                0.11.0               py39_cu113    pytorch
torchvision               0.12.0               py39_cu113    pytorch
tornado                   6.1              py39h27cfd23_0  
tqdm                      4.64.0           py39h06a4308_0  
traitlets                 5.1.1              pyhd3eb1b0_0  
typed-argument-parser     1.7.2                    pypi_0    pypi
typed-ast                 1.4.3            py39h7f8727e_1  
typing-extensions         4.1.1                hd3eb1b0_0  
typing-inspect            0.7.1                    pypi_0    pypi
typing_extensions         4.1.1              pyh06a4308_0  
tzdata                    2022a                hda174b7_0  
urllib3                   1.26.9           py39h06a4308_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39h06a4308_1  
websocket-client          0.58.0           py39h06a4308_4  
werkzeug                  2.0.3              pyhd3eb1b0_0  
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.2            py39h06a4308_0  
wrapt                     1.13.3           py39h7f8727e_2  
x264                      1!157.20191217       h7b6447c_0  
xarray                    2022.3.0                 pypi_0    pypi
xz                        5.2.5                h7f8727e_1  
yaml                      0.2.5                h7b6447c_0  
yarl                      1.6.3            py39h27cfd23_0  
zeromq                    4.3.4                h2531618_0  
zipp                      3.8.0            py39h06a4308_0  
zlib                      1.2.12               h7f8727e_2  
zstd                      1.4.9                haebb681_0  
```
- OS Debian GNU/Linux

**Checklist**

- [x] all dependencies are satisifed: `conda list` shows the packages listed in the `README`
- [x] the unit tests are working: `pytest -v` reports no errors

**Comment by cjmcgill** [comment]
@muammar thanks for posting. You are correct that we want to allow for gaps in the calibration set, same as regular targets. We will add in the proper masking for this for the various methods.

**Comment by muammar** [comment]
Thanks for your fast reply, @cjmcgill. That would be very useful because sometimes there is not enough data to make the dropping of `None` a viable solution.

**Comment by cjmcgill** [comment]
#295 has been merged, and should address this issue. If you notice failures going forward please open a new issue or reopen this one. Thanks!

**Comment by muammar** [comment]
> #295 has been merged, and should address this issue. If you notice failures going forward please open a new issue or reopen this one. Thanks!

I tried it today installing from source with `pip install -e .` and the calibration is working now. Thanks for your fast reply, @cjmcgill 

Best,
