### ISSUE TITLE
[BUG]: save_smiles_splits incompatible with features loaded from .npy files

### ISSUE THREAD

**Issue by oiao** [chemprop/chemprop#336]
It seems like there is a bug when the `--save_smiles_splits` keyword is requested in combination with a `--features_path` that loads features from *.npy* files. Looks like the saving routine can only deal with a CSV reader. See traceback:

``` python
Traceback (most recent call last):
  File "mambaforge/envs/chemprop/bin/chemprop_train", line 33, in <module>
    sys.exit(load_entry_point('chemprop', 'console_scripts', 'chemprop_train')())
  File "chemprop/chemprop/train/cross_validate.py", line 206, in chemprop_train
    cross_validate(args=TrainArgs().parse_args(), train_func=run_training)
  File "chemprop/chemprop/utils.py", line 540, in wrap
    result = func(*args, **kwargs)
  File "chemprop/chemprop/train/cross_validate.py", line 117, in cross_validate
    model_scores = train_func(args, data, logger)
  File "chemprop/chemprop/train/run_training.py", line 111, in run_training
    save_smiles_splits(
  File "chemprop/chemprop/utils.py", line 609, in save_smiles_splits
    feat_header = next(reader)
  File "mambaforge/envs/chemprop/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
```
This works fine if either `--save_smiles_splits` is not requested, or the provided features are stored as a csv.

**Comment by shihchengli** [comment]
@oiao The bug has been fixed by #337. If you notice failures going forward, please open a new issue or reopen this one. Thanks!
