### ISSUE TITLE
[BUG]: loss_function = 'evidential' causes a ValueError that does not happen with loss_function = 'mse', exact same data

### ISSUE THREAD

**Issue by GLPG-GT** [chemprop/chemprop#348]
We are training a regression model from a python script (not command line), using `TrainArgs()` stored into `args`, and:

`cross_validate(args = args, train_func = run_training)`

When we use:

`args.loss_function = 'mse'`

the model is trained correctly and there is no problem at all.
Instead, when we use:

`args.loss_function = 'evidential'`

the process starts correctly, but at some epoch of training the error text I quoted below is displayed, and the process stops.

This happens only with some specific datasets (meaning both the correct training when using `mse` and the error when using `evidential`, i.e. exact same data, process only differing by the setting of `loss_function`).
Unfortunately the data are proprietary, we cannot share them, nor can we make a smaller generic example, because we do not know what features of the data cause the issue.
Some more info on the data and process:
- we provide our own separate train, val and test files, no ensembling, no cross-validation
- the data are quite sparse, but there are no completely empty columns or rows

- python version 3.9
- package versions: 1.5.2
- OS ubuntu

```
> Traceback (most recent call last):
  File "/data/script.py", line 102, in <module>
    cross_validate(args = args, train_func = run_training)
  File "/home/ubuntu/anaconda3/envs/chemprop/lib/python3.9/site-packages/chemprop/utils.py", line 715, in wrap
    result = func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/chemprop/lib/python3.9/site-packages/chemprop/train/cross_validate.py", line 121, in cross_validate
    model_scores = train_func(args, data, logger)
  File "/home/ubuntu/anaconda3/envs/chemprop/lib/python3.9/site-packages/chemprop/train/run_training.py", line 286, in run_training
    val_scores = evaluate(
  File "/home/ubuntu/anaconda3/envs/chemprop/lib/python3.9/site-packages/chemprop/train/evaluate.py", line 123, in evaluate
    results = evaluate_predictions(
  File "/home/ubuntu/anaconda3/envs/chemprop/lib/python3.9/site-packages/chemprop/train/evaluate.py", line 82, in evaluate_predictions
    results[metric].append(metric_func(valid_targets[i], valid_preds[i]))
  File "/home/ubuntu/anaconda3/envs/chemprop/lib/python3.9/site-packages/chemprop/train/metrics.py", line 119, in rmse
    return mean_squared_error(targets, preds, squared=False)
  File "/home/ubuntu/anaconda3/envs/chemprop/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/chemprop/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 335, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "/home/ubuntu/anaconda3/envs/chemprop/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 90, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "/home/ubuntu/anaconda3/envs/chemprop/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/chemprop/lib/python3.9/site-packages/sklearn/utils/validation.py", line 720, in check_array
    _assert_all_finite(array,
  File "/home/ubuntu/anaconda3/envs/chemprop/lib/python3.9/site-packages/sklearn/utils/validation.py", line 103, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```
Any idea what may be causing this and how it can be fixed?
Thanks

**Comment by kevingreenman** [comment]
It's difficult to say for sure without being able to see the data and try it myself, but one possibility is that the `v` parameter in the [evidential loss](https://github.com/chemprop/chemprop/blob/98fc25eec8c57171c56d6ffad03ae1336c016e3b/chemprop/train/loss_functions.py#L327) is becoming extremely small, which would cause issues with the negative log likelihood portion of the loss function. 

Are you able to run your code in a debugger like VSCode or PyCharm where you can insert breakpoints and step through the code to determine where in Chemprop the NaN / Inf values are introduced?

**Comment by GLPG-GT** [comment]
Thank you Kevin.
A colleague of mine did some tests, I am going to report what he wrote:
> Kevin is correct, if we "clamp" v, it runs to the end
> the infs come from this line; `0.5 * torch.log(np.pi / v)`
> not sure if that is correct however, because the loss is negative at some point, which is somewhat odd

Unfortunately this is what we get.
I imagine we could share the numerical part of the data, after suppressing the column names, but we definitely could not share the smiles; if you think you could reproduce the same error by plugging in random all-different smiles, we could give it a try.
Although I imagine the specific code my colleague pinpointed should already help.
In the end, the data are what they are and they are valid (as they work with mse loss).

Thanks again for looking into this!
