### ISSUE TITLE
subprocess.CalledProcessError: Command '['git', 'remote', 'get-url', 'origin']'

### ISSUE THREAD

**Issue by fylinhub** [chemprop/chemprop#37]
Hello, 
I just re-install the new version of chemprop following the readme. But with this new version, I encountered this issue when I typed:
python train.py --data_path data/tox21.csv --dataset_type classification --save_dir tox21_checkpoints 

The full error messages are: 

Command line
python train.py --data_path data/tox21.csv --dataset_type classification --save_dir tox21_checkpoints
Args
{'activation': 'ReLU',
 'atom_messages': False,
 'batch_size': 50,
 'bias': False,
 'cache_cutoff': 10000,
 'checkpoint_dir': None,
 'checkpoint_path': None,
 'checkpoint_paths': None,
 'class_balance': False,
 'config_path': None,
 'crossval_index_dir': None,
 'crossval_index_file': None,
 'crossval_index_sets': None,
 'cuda': False,
 'data_path': 'data/tox21.csv',
 'dataset_type': 'classification',
 'depth': 3,
 'device': device(type='cpu'),
 'dropout': 0.0,
 'ensemble_size': 1,
 'epochs': 30,
 'features_generator': None,
 'features_only': False,
 'features_path': None,
 'features_scaling': True,
 'features_size': None,
 'ffn_hidden_size': 300,
 'ffn_num_layers': 2,
 'final_lr': 0.0001,
 'folds_file': None,
 'gpu': None,
 'hidden_size': 300,
 'init_lr': 0.0001,
 'log_frequency': 10,
 'max_data_size': None,
 'max_lr': 0.001,
 'metric': 'auc',
 'minimize_score': False,
 'multiclass_num_classes': 3,
 'no_cuda': False,
 'no_features_scaling': False,
 'num_folds': 1,
 'num_lrs': 1,
 'num_tasks': None,
 'num_workers': 8,
 'pytorch_seed': 0,
 'quiet': False,
 'save_dir': 'tox21_checkpoints/fold_0',
 'save_smiles_splits': False,
 'seed': 0,
 'separate_test_features_path': None,
 'separate_test_path': None,
 'separate_val_features_path': None,
 'separate_val_path': None,
 'show_individual_scores': False,
 'smiles_column': None,
 'split_sizes': (0.8, 0.1, 0.1),
 'split_type': 'random',
 'target_columns': None,
 'task_names': None,
 'test': False,
 'test_fold_index': None,
 'train_data_size': None,
 'undirected': False,
 'use_input_features': False,
 'val_fold_index': None,
 'warmup_epochs': 2.0}
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    cross_validate(args, logger)
  File "/opt/chemprop/chemprop/train/cross_validate.py", line 29, in cross_validate
    model_scores = run_training(args, logger)
  File "/opt/chemprop/chemprop/train/run_training.py", line 48, in run_training
    args.save(os.path.join(args.save_dir, 'args.json'))
  File "/opt/miniconda3/envs/chemprop/lib/python3.6/site-packages/tap/tap.py", line 445, in save
    json.dump(self._log_all(), f, indent=4, sort_keys=True, cls=PythonObjectEncoder)
  File "/opt/miniconda3/envs/chemprop/lib/python3.6/site-packages/tap/tap.py", line 277, in _log_all
    arg_log['reproducibility'] = self.get_reproducibility_info()
  File "/opt/miniconda3/envs/chemprop/lib/python3.6/site-packages/tap/tap.py", line 266, in get_reproducibility_info
    reproducibility['git_url'] = get_git_url(commit_hash=True)
  File "/opt/miniconda3/envs/chemprop/lib/python3.6/site-packages/tap/utils.py", line 65, in get_git_url
    url = check_output(['git', 'remote', 'get-url', 'origin'])
  File "/opt/miniconda3/envs/chemprop/lib/python3.6/site-packages/tap/utils.py", line 33, in check_output
    output = subprocess.check_output(command, stderr=devnull).decode('utf-8').strip()
  File "/opt/miniconda3/envs/chemprop/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/opt/miniconda3/envs/chemprop/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'remote', 'get-url', 'origin']' returned non-zero exit status 129.

Do you have any suggestions to get rid of this error? BTW, I didn't have such issue when I installed and used the earlier chemprop version in March. 

Other information if needed:
git config --get remote.origin.url, it shows:
https://github.com/chemprop/chemprop.git
git remote -v, it shows:
origin	https://github.com/chemprop/chemprop.git (fetch)
origin	https://github.com/chemprop/chemprop.git (push)
git version 1.8.3.1

Thank you!

**Comment by fylinhub** [comment]
just saw a solution from the the same issue that was closed, and I upgrade git to git-2.26.2, then there is no such error.
