### ISSUE TITLE
[BUG]: On clicking the button "Download Predictions" it gives error "Internal Server Error" .

### ISSUE THREAD

**Issue by avas27JTG** [chemprop/chemprop#437]
On clicking the button "Download Predictions" present on the predict page it gives error "Internal Server Error".
![image](https://github.com/chemprop/chemprop/assets/72438220/e4d756e2-ecf6-4a12-a71e-d4a2693dbbb7)

![image](https://github.com/chemprop/chemprop/assets/72438220/233c8c79-f047-4080-adb2-b0b8165fa68a)

Below is the server logs for this error.
```
[2023-08-03 13:52:20,935] ERROR in app: Exception on /download_predictions [GET]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/chemprop/chemprop/web/app/views.py", line 397, in download_predictions
    return send_from_directory(app.config['TEMP_FOLDER'], app.config['PREDICTIONS_FILENAME'], as_attachment=True, cache_timeout=-1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/werkzeug/utils.py", line 576, in send_from_directory
    return send_file(path, environ, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: send_file() got an unexpected keyword argument 'cache_timeout'
```

**Comment by Evert-Homan** [comment]
I have a similar issue. when trying to download results through the web interface (local installation, gunicorn):

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the `application.

 Can I fix this myself somehow?

Thanks/Evert

**Comment by kevingreenman** [comment]
@Evert-Homan the (partial) fix is implemented in #438. This hasn't been merged yet because we've requested changes from @avas27JTG. If you would like to implement the changes yourself, we would welcome a new PR from you to supersede #438.
