### ISSUE TITLE
[BUG]: MLPDS - Chemprop v2 only runs on yanked lightning versions

### ISSUE THREAD

**Issue by JenniferHem** [chemprop/chemprop#443]
**Describe the bug**
Trying to run chemprop2 alpha versions on anything but the old 2022.XX releases of lightning leads to Error: 

site-packages/pytorch_lightning/utilities/model_helpers.py", line 34, in is_overridden
    raise ValueError("Expected a parent")
ValueError: Expected a parent

**Example(s)**
See example script provided in the v2 subfolder

**Expected behavior**
v2 should work with the current stable releases of lightning (2.0.7) instead it only runs on 2022.10.25 which is a yanked release.

**Error Stack Trace**
```
File [~/miniconda3/envs/ML/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:466](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/hemmerj3/Code/chemprop2-playground/scripts/~/miniconda3/envs/ML/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:466), in Trainer.__init__(self, logger, enable_checkpointing, callbacks, default_root_dir, gradient_clip_val, gradient_clip_algorithm, num_nodes, num_processes, devices, gpus, auto_select_gpus, tpu_cores, ipus, enable_progress_bar, overfit_batches, track_grad_norm, check_val_every_n_epoch, fast_dev_run, accumulate_grad_batches, max_epochs, min_epochs, max_steps, min_steps, max_time, limit_train_batches, limit_val_batches, limit_test_batches, limit_predict_batches, val_check_interval, log_every_n_steps, accelerator, strategy, sync_batchnorm, precision, enable_model_summary, num_sanity_val_steps, resume_from_checkpoint, profiler, benchmark, deterministic, reload_dataloaders_every_n_epochs, auto_lr_find, replace_sampler_ddp, detect_anomaly, auto_scale_batch_size, plugins, amp_backend, amp_level, move_metrics_to_cpu, multiple_trainloader_mode, inference_mode)
    462 self._ckpt_path: Optional[str] = None
    464 # init callbacks
...
---> 34         raise ValueError("Expected a parent")
     36 from lightning_utilities.core.overrides import is_overridden as _is_overridden
     38 return _is_overridden(method_name, instance, parent)

ValueError: Expected a parent
```

**Environment**
- python version: 3.8
- package versions: lightning 1.9.5 (also occurs with 2.0.7), pytorch-lightning 1.9.5 
- OS: WSL with Ubuntu 22.04 LTS

**Comment by davidegraff** [comment]
what happens when you use `python >= 3.11` and `lightning >= 2.0`?

**Comment by JenniferHem** [comment]
Then I get: 

```
Cell In[2], line 9
      7 from chemprop.v2 import data as cp_data
      8 from chemprop.v2 import featurizers
----> 9 from chemprop.v2.models import modules, models
     10 import pandas as pd
     11 from chemprop_regressor import ChempropRegressor

File [~/Code/chemprop/chemprop/v2/models/__init__.py:9](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/hemmerj3/Code/chemprop2-playground/scripts/~/Code/chemprop/chemprop/v2/models/__init__.py:9)
      1 from .modules import (
      2     MessagePassingBlock,
      3     MolecularMessagePassingBlock,
   (...)
      7     BondMessageBlock,
      8 )
----> 9 from .models import (
     10     MPNN,
     11     ClassificationMPNN,
     12     BinaryClassificationMPNN,
     13     DirichletClassificationMPNN,
     14     MulticlassMPNN,
     15     DirichletMulticlassMPNN,
     16     RegressionMPNN,
     17     MveRegressionMPNN,
     18     SpectralMPNN,
     19 )

File [~/Code/chemprop/chemprop/v2/models/models/__init__.py:1](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/hemmerj3/Code/chemprop2-playground/scripts/~/Code/chemprop/chemprop/v2/models/models/__init__.py:1)
----> 1 from .base import MPNN
      2 from .classification import ClassificationMPNN, DirichletClassificationMPNN, BinaryClassificationMPNN
      3 from .multiclass import MulticlassMPNN, DirichletMulticlassMPNN

File [~/Code/chemprop/chemprop/v2/models/models/base.py:17](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/hemmerj3/Code/chemprop2-playground/scripts/~/Code/chemprop/chemprop/v2/models/models/base.py:17)
     13 from chemprop.v2.models.schedulers import NoamLR
     14 from chemprop.v2.models.utils import get_activation_function
---> 17 class MPNN(ABC, pl.LightningModule):
     18     """An `MPNN` is comprised of a `MessagePassingBlock` and an FFN top-model. The former
     19     calculates learned encodings from an input molecule/reaction graph, and the latter takes these
     20     encodings as input to calculate a final prediction. The full model is trained end-to-end.
   (...)
     28     parameterized distribution, e.g., MVE regression, for which `s` is 2. Typically, this is just 1.
     29     """
     31     def __init__(
     32         self,
     33         mpn_block: MessagePassingBlock,
   (...)
     46         final_lr: float = 1e-4,
     47     ):

AttributeError: module 'pytorch_lightning' has no attribute 'LightningModule'
```

with lightning version 2.0.7 and 1.9.5 as well.

**Comment by davidegraff** [comment]
it looks like there's currently a bug where the pre-release `v2` is using both `Lightning` and `PytorchLightning`. This should be fixed in the coming few days. In the meantime, the best bet is to replace all `pytorch_lightning` mentions with `lightning.pytorch` and remove the `pytorch_lightning` package.

**Comment by davidegraff** [comment]
Can you try rerunning this with the latest commit? The object model has changed quite a bit as the API is still experimental, but it shouldn’t be too different from a client perspective.

**Comment by JenniferHem** [comment]
Thanks. I just tried installing the branch again with the latest changes and I get this error. Really sorry but I also did not find anay part which could be changed to avoid this:

```
~/Code/chemprop (v2/dev)$ <base> pip install -e . --timeout=1000
Looking in indexes: https://.........../repository/python/simple
Obtaining file:///home/hemmerj3/Code/chemprop
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /home/hemmerj3/miniconda3/lib/python3.9/site-packages (from chemprop==1.5.1) (1.24.1)
Requirement already satisfied: rdkit in /home/hemmerj3/miniconda3/lib/python3.9/site-packages (from chemprop==1.5.1) (2023.3.1)
Requirement already satisfied: scipy in /home/hemmerj3/miniconda3/lib/python3.9/site-packages (from chemprop==1.5.1) (1.10.0)
Requirement already satisfied: pandas in /home/hemmerj3/miniconda3/lib/python3.9/site-packages (from chemprop==1.5.1) (1.5.2)
Requirement already satisfied: scikit-learn in /home/hemmerj3/miniconda3/lib/python3.9/site-packages (from chemprop==1.5.1) (1.2.2)
Collecting torch>=2.0
  Using cached https://nexus.roqs.basf.net/repository/python/packages/torch/2.0.1/torch-2.0.1-cp39-cp39-manylinux1_x86_64.whl (619.9 MB)
Collecting lightning>=2.0
  Using cached https://nexus.roqs.basf.net/repository/python/packages/lightning/2022.10.25/lightning-2022.10.25-py3-none-any.whl (2.1 MB)
ERROR: Package 'chemprop' requires a different Python: 3.9.15 not in '>=3.11'
```

I'll try to add the path to the package for now and see if this works.

**Comment by JenniferHem** [comment]
Trying the example script with the path set to the nev dev/v2 version gives:

```
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hemmerj3/miniconda3/envs/BASFchemprop/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/hemmerj3/miniconda3/envs/BASFchemprop/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemmerj3/miniconda3/envs/BASFchemprop/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/hemmerj3/Code/chemprop/chemprop/v2/data/datasets.py", line 144, in __getitem__
    mg = self.featurizer(d.mol, self.V_fs[idx], self.E_fs[idx])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hemmerj3/Code/chemprop/chemprop/v2/featurizers/molecule.py", line 87, in __call__
    n_atoms = mol.GetNumAtoms()
              ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'GetNumAtoms'
```

(using this as input just to test)

```
smiles,stuff
CCCCCCCCCCCCCCC,5
CCCCCCCCCCCCCCCCCC,30
CCCCCCCCCCF,2
CCCCCCN,4
CCCCCCCCCCCCCCC,5
CCCCCCCCCCCCCCCCCC,30
CCCCCCCCCCF,2
CCCCCCN,4
CCCCCCCCCCCCCCC,5
CCCCCCCCCCCCCCCCCC,30
CCCCCCCCCCF,2
CCCCCCN,4
CCCCCCCCCCCCCCC,5
CCCCCCCCCCCCCCCCCC,30
CCCCCCCCCCF,2
CCCCCCN,4
CCCCCCCCCCCCCCC,5
CCCCCCCCCCCCCCCCCC,30
CCCCCCCCCCF,2
CCCCCCN,4
CCCCCCCCCCCCCCC,5
CCCCCCCCCCCCCCCCCC,30
CCCCCCCCCCF,2
CCCCCCN,4
```

**Comment by davidegraff** [comment]
Ah yes, that's because the API has changed. With the most recent commit on the `v2/dev` branch, `MoleculeDatapoint`s are RDKit `Mol`-centric (as per #407). I.e., they should now be created like so:
```python
smis: list[str]
ys: ArrayLike
mols = [Chem.MolFromSmiles(smi) for smi in smis]
datapoints = [MoleculeDatapoint(mol, y) for mol, y in zip(mols, ys)]
```
or like so:
```python
datapoints = [MoleculeDatapoint.from_smi(smi, y) for smi, y in zip(smis, ys)]
```
_Note_: the `keep_h` and `add_h` args from the initializer have now been moved to keyword arguments in the `MoleculeDatapoint.from_smi` method. All other positional and keyword arguments in `from_smi` match up with those in `__init__` (except, of course, the `mol` argument)

**Comment by JenniferHem** [comment]
Thanks for the Answer I'll test that out. I like the change that would allow to also have a MoleculeDatapoint.from_rdkit(smi, y)-like functionality as suggested in #407? :)

**Comment by davidegraff** [comment]
Hi- just checking to see if your code works now with the latest commit on `v2/dev`?

**Comment by JenniferHem** [comment]
Hi really sorry it was a bit hectic these days. I am not sure if I tested it but I'll check as soon as I can.
