### ISSUE TITLE
Can't pickle local object/EOF error during predict.py

### ISSUE THREAD

**Issue by nanopoop** [chemprop/chemprop#50]
I am trying to run the predict.py script on a trained model, but am getting an error after loading the data and pretrained parameters. I'm running on Windows 10 with a CPU. I've been able to use previous versions of chemprop with no issues, but I updated to the newest version recently and ran into this one. Thanks

Update - I get same error when running interpret.py. 

Loading training args
Loading data
21it [00:00, ?it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<?, ?it/s]
Validating SMILES
Test size = 21
Predicting with an ensemble of 1 models
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]Loading pretrained parameter "encoder.encoder.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.W_i.weight".
Loading pretrained parameter "encoder.encoder.W_h.weight".
Loading pretrained parameter "encoder.encoder.W_o.weight".
Loading pretrained parameter "encoder.encoder.W_o.bias".
Loading pretrained parameter "ffn.1.weight".
Loading pretrained parameter "ffn.1.bias".
Loading pretrained parameter "ffn.4.weight".
Loading pretrained parameter "ffn.4.bias".

  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "predict.py", line 8, in <module>
    make_predictions(args)
  File "C:\chemprop\chemprop\train\make_predictions.py", line 87, in make_predictions
    scaler=scaler
  File "C:\chemprop\chemprop\train\predict.py", line 28, in predict
    for batch in tqdm(data_loader, disable=disable_progress_bar):
  File "\anaconda3\envs\chemprop\lib\site-packages\tqdm\std.py", line 1129, in __iter__
    for obj in iterable:
  File "C:\chemprop\chemprop\data\data.py", line 388, in __iter__
    return super(MoleculeDataLoader, self).__iter__()
  File "\anaconda3\envs\chemprop\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "\anaconda3\envs\chemprop\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "\anaconda3\envs\chemprop\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "\anaconda3\envs\chemprop\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "\anaconda3\envs\chemprop\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "\anaconda3\envs\chemprop\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "\anaconda3\envs\chemprop\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'MoleculeDataLoader.__init__.<locals>.construct_molecule_batch'

(chemprop) C:\chemprop>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "\anaconda3\envs\chemprop\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "\anaconda3\envs\chemprop\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by nanopoop** [comment]
Changing the num_workers argument to 0 seems to have fixed my issue. Thanks

**Comment by swansonk14** [comment]
Hi @nanopoop, thanks for raising the issue! I attempted to fix that pickling issue in this commit https://github.com/chemprop/chemprop/commit/ce317b23a9a0bdf0d7a5dc97f0e002b8f1fc46e0 so hopefully that will solve the problem, but if it doesn't, then you've already found the next best solution: just set num_workers to 0. The problem is related to the way that PyTorch does parallel DataLoading and so the solution is to simply turn off the parallel data loading by setting the number of workers to 0.
