### ISSUE TITLE
[QUESTION]: Too many files open error?

### ISSUE THREAD

**Issue by norsedrunkensailor** [chemprop/chemprop#595]
**What are you trying to do?**
I'm trying a simple regression task on a set of compounds I've curated. Consistently, it reaches a certain epoch and then gives a "OSError: [Errno 24] Too many open files" error. How do I proceed? 

I have checked that I have no RAM overflow errors, nor is the CPU overloaded. 

**Previous attempts**
The issue seems circumvented when I reduce the number of target columns. Although, why this is the case is unclear to me

`chemprop_train --data_path data/df_binding_data_only_top5.csv --dataset_type regression --save_dir binding_top5_checkpoints_v2 --features_generator rdkit_2d_normalized --target_columns CHEMBL217 CHEMBL234 CHEMBL214 CHEMBL251 CHEMBL256 --split_type scaffold_balanced --no_features_scaling --no_cache_mol --num_workers 6`

Suddenly, in Epoch 11:
Epoch 11
 37%|██████████████████████████████████▊                                                            | 11/30 [27:52<48:08, 152.03s/it]
Traceback (most recent call last):                                                                                                   
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/chemprop_train", line 8, in <module>
    sys.exit(chemprop_train())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chemprop/train/cross_validate.py", line 208, in chemprop_train
    cross_validate(args=TrainArgs().parse_args(), train_func=run_training)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chemprop/utils.py", line 591, in wrap
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chemprop/train/cross_validate.py", line 119, in cross_validate
    model_scores = train_func(args, data, logger)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chemprop/train/run_training.py", line 295, in run_training
    n_iter = train(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chemprop/train/train.py", line 53, in train
    for batch in tqdm(data_loader, total=len(data_loader), leave=False):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chemprop/data/data.py", line 945, in __iter__
    return super(MoleculeDataLoader, self).__iter__()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1034, in __init__
    w.start()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 54, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files

**Comment by JacksonBurns** [comment]
Nkte for developers: possibly related, from PyTorch: https://github.com/pytorch/pytorch/issues/11201

**Comment by JacksonBurns** [comment]
Hi @norsedrunkensailor from your stack trace it seems like you are running Chemprop in Python 3.10 - our unit tests do not work on versions greater than 3.8 (although chemprop itself builds), so we don't have the capacity to debug this error. We suggest you re-install chemprop on Python 3.7 and 3.8 and try to reproduce the error there.

This came up on another issue with running Chemprop in versions of Python greater than 3.8 recently (see https://github.com/chemprop/chemprop/issues/565#issuecomment-1917061892) and we decided that, going forward, we will explicitly only allow building Chemprop on python 3.7 or 3.8. The upcoming release of Chemprop v2 will support Python 3.11 and newer.

Please re-open or open a new issue if this error persists in the supported versions of Python.

**Comment by norsedrunkensailor** [comment]
Thank you! I'll make sure to stick with python 3.8
