### ISSUE TITLE
[BUG]: supplied --constraints_path is not used during atom target predictions

### ISSUE THREAD

**Issue by priabb** [chemprop/chemprop#724]
When making predictions for atom targets on a new dataset, I am supplying a --constraints_path for the new dataset. However, the trained model is not using the new path for constraints but is trying to use the --constraints_path that was used during training.

Traceback (most recent call last):
chemprop.train.make_predictions(args=args)
  File "/github_repos/chemprop/chemprop/utils.py", line 591, in wrap
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/github_repos/chemprop/chemprop/train/make_predictions.py", line 465, in make_predictions
    preds, unc = predict_and_save(
                 ^^^^^^^^^^^^^^^^^
  File "/github_repos/chemprop/chemprop/train/make_predictions.py", line 160, in predict_and_save
    estimator = UncertaintyEstimator(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/github_repos/chemprop/chemprop/uncertainty/uncertainty_estimator.py", line 29, in __init__
    self.predictor = build_uncertainty_predictor(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github_repos/chemprop/chemprop/uncertainty/uncertainty_predictor.py", line 1430, in build_uncertainty_predictor
    predictor = predictor_class(
                ^^^^^^^^^^^^^^^^
  File "/github_repos/chemprop/chemprop/uncertainty/uncertainty_predictor.py", line 52, in __init__
    self.calculate_predictions()
  File "/github_repos/chemprop/chemprop/uncertainty/uncertainty_predictor.py", line 120, in calculate_predictions
    for i, (model, scaler_list) in enumerate(
  File "/miniconda3/envs/chemprop/lib/python3.11/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/github_repos/chemprop/chemprop/train/make_predictions.py", line 36, in <genexpr>
    load_checkpoint(checkpoint_path, device=args.device) for checkpoint_path in args.checkpoint_paths
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github_repos/chemprop/chemprop/utils.py", line 121, in load_checkpoint
    model = MoleculeModel(args)
            ^^^^^^^^^^^^^^^^^^^
  File "/github_repos/chemprop/chemprop/models/model.py", line 45, in __init__
    args.atom_constraints,
    ^^^^^^^^^^^^^^^^^^^^^
  File "/github_repos/chemprop/chemprop/args.py", line 605, in atom_constraints
    header = chemprop.data.utils.get_header(self.constraints_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github_repos/chemprop/chemprop/data/utils.py", line 32, in get_header
    with open(path) as f:
         ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'constraints_train.csv'

**Comment by priabb** [comment]
yes

**Comment by JacksonBurns** [comment]
@priabb Chemprop v1 is only tested and supported on Python version 3.7 and 3.8 (our latest `setup.py` actually _prevents_ you from installing other versions), so this is not an error we can address.

Please try and reproduce this error on a supported version of Python with the latest release of Chemprop v1 and re-open an issue if it persists. I will note that, because the development team is focused on v2, we will likely not be able to fix this ourselves but may be able to review a community-contributed fix.
