### ISSUE TITLE
[QUESTION]: Run train.py with 'mps' GPU

### ISSUE THREAD

**Issue by Thanh-An-Pham** [chemprop/chemprop#751]
I am trying to run the training command:
`python train.py --data_path zinc_250k_prop.csv --dataset_type regression --save_dir zinc_prop --seed 42 --gpu -1 `

The error I encountered was: `train.py: error: argument --gpu: invalid choice: -1 (choose from )`
I had change -1 to 0 but not working. Thank you for ur help
Additionally, I saw a argument `--no_cuda`, since the M1 chip do not have CUDA, should i use it ?
Thank you very much for ur help.

**Comment by shihchengli** [comment]
I believe Chemprop v1 only supports CPU and GPU. If you are interested in using other accelerators (e.g., TPU, MPS), you might consider our v2 version. However, there is a known issue with using MPS in our v2, as mentioned in #711. Once this issue is resolved, you should be able to use your MPS to train your model. On the other hand, for v1, you don't need to specifically specify `--no_cuda` if you don't have CUDA support. It will automatically detect it via `torch.cuda.is_available()`. The `--gpu` option is used to specify which GPU you want to use, not the number of GPUs. Hope this helps!

**Comment by Thanh-An-Pham** [comment]
Thank you so much for ur quick respond,
I have installed the v2 version and able to accelerate by the MPS gpu.
But i end up with the error as you gave, since i run this command in terminal, i can not add the command to notebook like instruction. Here is the Traceback: 
`Sanity Checking: |                                                                                                                                                                                           | 0/? [00:00<?, ?it/s]/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/bin/chemprop", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/chemprop/cli/main.py", line 80, in main
    func(args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/chemprop/cli/train.py", line 61, in func
    main(args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/chemprop/cli/train.py", line 839, in main
    train_model(args, train_loader, val_loader, test_loader, output_dir, scaler, input_scalers)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/chemprop/cli/train.py", line 748, in train_model
    trainer.fit(model, train_loader, val_loader)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1031, in _run_stage
    self._run_sanity_check()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1060, in _run_sanity_check
    val_loop.run()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 370, in _evaluation_step
    batch = call._call_strategy_hook(trainer, "batch_to_device", batch, dataloader_idx=dataloader_idx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/strategies/strategy.py", line 278, in batch_to_device
    return model._apply_batch_transfer_handler(batch, device=device, dataloader_idx=dataloader_idx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/core/module.py", line 347, in _apply_batch_transfer_handler
    batch = self._call_batch_hook("transfer_batch_to_device", batch, device, dataloader_idx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/core/module.py", line 336, in _call_batch_hook
    return trainer_method(trainer, hook_name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/pytorch/core/hooks.py", line 613, in transfer_batch_to_device
    return move_data_to_device(batch, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/fabric/utilities/apply_func.py", line 103, in move_data_to_device
    return apply_to_collection(batch, dtype=_TransferableDataType, function=batch_to)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning_utilities/core/apply_func.py", line 72, in apply_to_collection
    return _apply_to_collection_slow(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning_utilities/core/apply_func.py", line 125, in _apply_to_collection_slow
    v = _apply_to_collection_slow(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning_utilities/core/apply_func.py", line 96, in _apply_to_collection_slow
    return function(data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/decompose/lib/python3.11/site-packages/lightning/fabric/utilities/apply_func.py", line 97, in batch_to
    data_output = data.to(device, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.`
Should i. add the `torch.set_default_dtype(torch.float32)` in the train.py ? or do i need to add anywhere else? 
Thanks in advances.

**Comment by shihchengli** [comment]
@Thanh-An-Pham I'm not sure if it will solve your problem, but you can try it. We will continue working on this issue and let you know when we resolve it.

**Comment by shihchengli** [comment]
@Thanh-An-Pham I think you should be able to run it now.
