### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied (64x2348 and 300x300)

### ISSUE THREAD

**Issue by AquifersBSIM** [chemprop/chemprop#925]
Hello! I am trying to add the molecule featurizers as documented in the latest chemprop documentations. However, whenever i try to run training, the following traceback error pops up. Keep in mind I followed everything in the training chemprop documentations!

```
Traceback (most recent call last):
  File "/fred/oz241/BSIM/prototype_files/sdf_to_smi_test/test/test8.py", line 242, in <module>
    main()
  File "/fred/oz241/BSIM/prototype_files/sdf_to_smi_test/test/test8.py", line 237, in main
    training_function(smis, yss, mol_weights, log_ps)
  File "/fred/oz241/BSIM/prototype_files/sdf_to_smi_test/test/test8.py", line 190, in training_function
    trainer.fit(mpnn, train_loader, val_loader)
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1031, in _run_stage
    self._run_sanity_check()
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1060, in _run_sanity_check
    val_loop.run()
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/lightning/pytorch/strategies/strategy.py", line 412, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/chemprop/chemprop/models/model.py", line 157, in validation_step
    losses = self._evaluate_batch(batch)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/chemprop/chemprop/models/model.py", line 180, in _evaluate_batch
    preds = self(bmg, V_d, X_d)
            ^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/chemprop/chemprop/models/model.py", line 136, in forward
    return self.predictor(self.fingerprint(bmg, V_d, X_d))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/chemprop/chemprop/nn/predictors.py", line 148, in forward
    return self.output_transform(self.ffn(Z))
                                 ^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/bsim_chemprop/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x2348 and 300x300)
```

This is my temporary test function:

```
def training_function(smis, yss, mol_weights, log_ps):
    
    # Molecule Featurizer

    molecule_featurizer = MorganBinaryFeaturizer()
    extra_datapoint_descriptors = [molecule_featurizer(utils.make_mol(smi, keep_h=False, add_h=False)) for smi in smis]

    molecule_featurizer = MorganCountFeaturizer(radius=2, length=2048, include_chirality=True)

    # Molecule datapoint

    all_data = [data.MoleculeDatapoint.from_smi(
        smi, y, weight=mol_weight, x_d=x_d) for smi, y, mol_weight, x_d in zip(smis, yss, mol_weights, extra_datapoint_descriptors)]

    #________________________________________________________________________________________________________________________________
    # Testing phase

    num_workers = 4 # number of workers for dataloader. 0 means using main process for data loading

    mols = [d.mol for d in all_data]  # RDkit Mol objects are use for structure based splits
    train_indices, val_indices, test_indices = data.make_split_indices(mols, "random", (0.8, 0.1, 0.1))
    train_data, val_data, test_data = data.split_data_by_indices(
        all_data, train_indices, val_indices, test_indices
    )

    # Bond & Atom featurizer

    atom_featurizer = MultiHotAtomFeaturizer.v2()
    featurizer = featurizers.SimpleMoleculeMolGraphFeaturizer(atom_featurizer=atom_featurizer)

    #featurizer = featurizers.SimpleMoleculeMolGraphFeaturizer()

    train_dset = data.MoleculeDataset(train_data, featurizer)
    scaler = train_dset.normalize_targets()

    val_dset = data.MoleculeDataset(val_data, featurizer)
    val_dset.normalize_targets(scaler)

    test_dset = data.MoleculeDataset(test_data, featurizer)

    train_loader = data.build_dataloader(train_dset, num_workers=num_workers)
    val_loader = data.build_dataloader(val_dset, num_workers=num_workers, shuffle=False)
    test_loader = data.build_dataloader(test_dset, num_workers=num_workers, shuffle=False)


    # Aggregation

    agg = NormAggregation()

    # Feed forward network (FFN)

    # Scaling the X_d input

    X_d_scaler = train_dset.normalize_inputs("X_d")
    val_dset.normalize_inputs("X_d", X_d_scaler)

    X_d_transform = ScaleTransform.from_standard_scaler(X_d_scaler)

    # Scaling the V_d

    #V_d_scaler = train_dset.normalize_inputs("V_d")
    #val_dset.normalize_inputs("V_d", V_d_scaler)

    #V_d_transform = ScaleTransform.from_standard_scaler(V_d_scaler)

    mp = BondMessagePassing()

    # Scaling the targets

    output_scaler = train_dset.normalize_targets()

    output_transform = UnscaleTransform.from_standard_scaler(output_scaler)

    ffn = RegressionFFN(output_transform=output_transform)

    # Batch norm

    batch_norm = True

    # Metrics

    metric_list = [nn.metrics.RMSEMetric(), nn.metrics.MAEMetric()] # Only the first metric is used for training and early stopping

    # Constructs MPNN

    mpnn = models.MPNN(mp, agg, ffn, batch_norm, metric_list, X_d_transform=X_d_transform)

    checkpointing = ModelCheckpoint(
        dirpath="mycheckpoints",
        filename="best-{epoch}-{val_loss:.2f}",
        monitor="val_loss",
        mode="min",
        save_last=True,
    )

    trainer = Trainer(
        callbacks=[checkpointing],
        logger=False,
        enable_progress_bar=True,
        accelerator="auto",
        devices=1,
        max_epochs=75
        )

    trainer.fit(mpnn, train_loader, val_loader)

    results = trainer.test(mpnn, test_loader)

    print(results)
```

**Comment by AquifersBSIM** [comment]
Hi @JacksonBurns , Thank you so much for your quick response! Just wondering, if I were to have any problems like this in the future, would it be better if I posted it in the discussion tab?

**Comment by kevingreenman** [comment]
Either place is fine, but IMO, questions like yours with a specific chemprop error message belong more as issues, while discussions are more for broad questions (these might not have a definitive correct answer or might relate to asking about best practices).

**Comment by AquifersBSIM** [comment]
Thank you @kevingreenman and @JacksonBurns again for the replies!

**Comment by yyyzzz111** [comment]
How can I change input_dim to match the potential size of the RegressionFFN messaging layer? I copied ffn's source code and changed input_dim=301 directly, but he also reported an error
 File D:\py\Anaconda3\envs\chemprop\Lib\site-packages\torch\nn\modules\module.py:1931, in Module .__getattr__(self, name)
   1929 if name in modules.
   1930 return modules[name]
-> 1931 raise AttributeError(
   1932 f"'{type(self). __name__}' object has no attribute '{name}'”
   1933 )

AttributeError: 'FFN' object has no attribute 'hparams' 1933 )

**Comment by JacksonBurns** [comment]
@yyyzzz111 please open a new issue with the code you are trying to execute and the complete stacktrace
