### ISSUE TITLE
How do I implement V_d into a trainer?

### ISSUE THREAD

**Issue by AquifersBSIM** [chemprop/chemprop#926]
Hello guys! I have a question and possibly an issue, What exactly are V_d and how do I implement it into my trainer? I have generated LogP (lipophilicity) and I believe it is an extra atom descriptors (V_d). This is the traceback error that I got:

```
Traceback (most recent call last):
  File "/fred/oz241/BSIM/prototype_files/sdf_to_smi_test/test/test2.py", line 241, in <module>
    main()
  File "/fred/oz241/BSIM/prototype_files/sdf_to_smi_test/test/test2.py", line 236, in main
    training_function(smis, yss, mol_weights, log_ps)
  File "/fred/oz241/BSIM/prototype_files/sdf_to_smi_test/test/test2.py", line 146, in training_function
    V_d_scaler = train_dset.normalize_inputs("V_d")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/chemprop/chemprop/data/datasets.py", line 287, in normalize_inputs
    X = None if self.d_vd == 0 else np.concatenate(self.V_ds, axis=0)
                ^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/chemprop/chemprop/data/datasets.py", line 272, in d_vd
    return 0 if self.V_ds[0] is None else self.V_ds[0].shape[1]
                                          ~~~~~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range
```

This is my temporary training function:

```
def training_function(smis, yss, mol_weights, log_ps):
    
    # Molecule Featurizer

    molecule_featurizer = MorganBinaryFeaturizer()
    extra_datapoint_descriptors = [molecule_featurizer(utils.make_mol(smi, keep_h=False, add_h=False)) for smi in smis]

    molecule_featurizer = MorganCountFeaturizer(radius=2, length=2048, include_chirality=True)

    # Molecule datapoint

    all_data = [data.MoleculeDatapoint.from_smi(
        smi, y, weight=mol_weight, x_d=x_d, V_d=log_p) for smi, y, mol_weight, x_d, log_p in zip(smis, yss, mol_weights, extra_datapoint_descriptors, log_ps)]

    print(all_data[0])

    #________________________________________________________________________________________________________________________________
    # Testing phase

    num_workers = 4 # number of workers for dataloader. 0 means using main process for data loading

    mols = [d.mol for d in all_data]  # RDkit Mol objects are use for structure based splits
    train_indices, val_indices, test_indices = data.make_split_indices(mols, "random", (0.8, 0.1, 0.1))
    train_data, val_data, test_data = data.split_data_by_indices(
        all_data, train_indices, val_indices, test_indices
    )

    # Bond & Atom featurizer

    atom_featurizer = MultiHotAtomFeaturizer.v2()
    featurizer = featurizers.SimpleMoleculeMolGraphFeaturizer(atom_featurizer=atom_featurizer)

    #featurizer = featurizers.SimpleMoleculeMolGraphFeaturizer()

    train_dset = data.MoleculeDataset(train_data, featurizer)
    scaler = train_dset.normalize_targets()

    val_dset = data.MoleculeDataset(val_data, featurizer)
    val_dset.normalize_targets(scaler)

    test_dset = data.MoleculeDataset(test_data, featurizer)

    train_loader = data.build_dataloader(train_dset, num_workers=num_workers)
    val_loader = data.build_dataloader(val_dset, num_workers=num_workers, shuffle=False)
    test_loader = data.build_dataloader(test_dset, num_workers=num_workers, shuffle=False)


    # Aggregation

    agg = NormAggregation()

    # Scaling the X_d input

    X_d_scaler = train_dset.normalize_inputs("X_d")
    val_dset.normalize_inputs("X_d", X_d_scaler)

    X_d_transform = ScaleTransform.from_standard_scaler(X_d_scaler)

    # Scaling the V_d

    V_d_scaler = train_dset.normalize_inputs("V_d")
    val_dset.normalize_inputs("V_d", V_d_scaler)

    V_d_transform = ScaleTransform.from_standard_scaler(V_d_scaler)

    mp = BondMessagePassing()

    # Scaling the targets

    output_scaler = train_dset.normalize_targets()

    output_transform = UnscaleTransform.from_standard_scaler(output_scaler)

    # Feed forward network (FFN)

    ffn = RegressionFFN(output_transform=output_transform, input_dim=2348) # Increased the input_dim to 2348 to suit the dims

    # Batch norm

    batch_norm = True

    # Metrics

    metric_list = [nn.metrics.RMSEMetric(), nn.metrics.MAEMetric()] # Only the first metric is used for training and early stopping

    # Constructs MPNN

    mpnn = models.MPNN(mp, agg, ffn, batch_norm, metric_list, X_d_transform=X_d_transform, V_d_transform=V_d_transform)

    checkpointing = ModelCheckpoint(
        dirpath="mycheckpoints",
        filename="best-{epoch}-{val_loss:.2f}",
        monitor="val_loss",
        mode="min",
        save_last=True,
    )

    trainer = Trainer(
        callbacks=[checkpointing],
        logger=False,
        enable_progress_bar=True,
        accelerator="auto",
        devices=1,
        max_epochs=75
        )

    trainer.fit(mpnn, train_loader, val_loader)

    results = trainer.test(mpnn, test_loader)

    print(results)
```

**Comment by KnathanM** [comment]
> What exactly are V_d and how do I implement it into my trainer?

You have it correct that V_d are extra atom descriptors. V_d is "a numpy array of shape ``V x d_vd``, where ``V`` is the number of atoms in the molecule, and ``d_vd`` is the number of additional descriptors that will be concatenated to atom-level  descriptors after message passing" (taken from the MoleculDatapoint [docstring](https://chemprop.readthedocs.io/en/latest/autoapi/chemprop/data/datapoints/index.html#chemprop.data.datapoints.MoleculeDatapoint)). If each atom in a molecule has a `LogP` value, you could use it as an extra atom descriptor. If it is molecule level descriptor, you would concatenate it to `mol_weights` before passing it as `x_d`. 

These other two resources can help you with extra features/descriptors. 
https://chemprop.readthedocs.io/en/latest/tutorial/python/data/datapoints.html#Extra-features-and-descriptors
https://github.com/chemprop/chemprop/blob/ffd11078effcbe3e648742d20c27f447c2343ac4/examples/extra_features_descriptors.ipynb

**Comment by AquifersBSIM** [comment]
Thank you for the reply @KnathanM ! Basically, all the V_d, V_f and E_f are at the atom level instead of molecule level.

**Comment by KnathanM** [comment]
Yes, V_d and V_f are at the atom level while E_f is at the bond level. 

We can put this more generally because the MPNN architecture works for all graphs (not just molecules represented as graphs).   V_d and V_f are at the **V**ertex level of the graph, E_f is at the **E**dge level of the graph, and x_d is at the datapoint level (could be a single graph or multiple graphs that share a target value).

**Comment by AquifersBSIM** [comment]
I have tried concatenating logP to mol_weights, but it doesnt seems to work, the resources given by @KnathanM are amazing but I definitely need a someone to tell me what's wrong. The following traceback is what I got:
```
Traceback (most recent call last):
  File "/fred/oz241/BSIM/prototype_files/gen_smi/Brendan/COX2/vinardo/test2.py", line 157, in <module>
    main()
  File "/fred/oz241/BSIM/prototype_files/gen_smi/Brendan/COX2/vinardo/test2.py", line 152, in main
    training_function(smis, yss, mol_weights, log_ps)
  File "/fred/oz241/BSIM/prototype_files/gen_smi/Brendan/COX2/vinardo/test2.py", line 110, in training_function
    all_data = [data.MoleculeDatapoint.from_smi(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/prototype_files/gen_smi/Brendan/COX2/vinardo/test2.py", line 110, in <listcomp>
    all_data = [data.MoleculeDatapoint.from_smi(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fred/oz241/BSIM/conda_chemprop/chemprop/chemprop/data/datapoints.py", line 65, in from_smi
    return cls(mol, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 14, in __init__
  File "/fred/oz241/BSIM/conda_chemprop/chemprop/chemprop/data/datapoints.py", line 98, in __post_init__
    super().__post_init__(mfs)
  File "/fred/oz241/BSIM/conda_chemprop/chemprop/chemprop/data/datapoints.py", line 45, in __post_init__
    self.x_d[np.isnan(self.x_d)] = NAN_TOKEN
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.float64' object does not support item assignment
```

Example code:

```
# Example data
log_ps = [2.278, 2.871, 2.753, 2.065, 1.79, 3.07]
mol_weights = [100.1, 150.2, 125.6, 110.3, 90.5, 140.0]

# Convert to numpy arrays and ensure they are at least 1-dimensional
log_ps = np.array(log_ps)
log_ps = np.atleast_1d(log_ps).squeeze()
mol_weights = np.array(mol_weights)
mol_weights = np.atleast_1d(mol_weights)

# Print to verify
print(f"LogP: {log_ps}")
print(f"mol weight: {mol_weights}")

# Concatenate log_p and mol_weight
extra_datapoint_descriptors = np.concatenate((log_ps, mol_weights))

print(f"Combined: {extra_datapoint_descriptors}")

all_data = [data.MoleculeDatapoint.from_smi(
            smi, y, x_d=X_d) for smi, y, X_d  in zip(smis, yss, extra_datapoint_descriptors)]
```

**Comment by AquifersBSIM** [comment]
I managed to concatenate LogP to mol_weights right, but how do I concatenate the Morgan fingerprint featurizers (```morFs```) because the size of ```morFs``` is huge right? I am abit clueless here!

**Comment by KnathanM** [comment]
Looking again at your original code
```
all_data = [
        data.MoleculeDatapoint.from_smi(smi, y, weight=mol_weight, x_d=x_d, V_d=log_p)
        for smi, y, mol_weight, x_d, log_p in zip(smis, yss, mol_weights, extra_datapoint_descriptors, log_ps)
    ]
```
I should also clarify that `weight=` is not related to the molecular weight, it is the weight of the datapoint in the loss function. If you had some datapoints you knew were less likely to be correct, you could weight them less during training. 

As for how to concatenate the Morgan fingerprints with the LogP and mol_weights:
```
molecule_featurizer = featurizers.MorganBinaryFeaturizer()
morgan_fingerprints= np.array([molecule_featurizer(utils.make_mol(smi, keep_h=False, add_h=False)) for smi in smis])

# Replace with numpy arrays of the same shape but with your actual data.
LogP = np.random.rand(len(mols), 1)
mol_weights = np.random.rand(len(mols), 1)

extra_datapoint_descriptors = np.concatenate(
    [morgan_fingerprints, LogP , mol_weights], axis=1
)

all_data = [
        data.MoleculeDatapoint.from_smi(smi, y, x_d=x_d)
        for smi, y, x_d in zip(smis, yss, extra_datapoint_descriptors)
    ]
```

**Comment by AquifersBSIM** [comment]
Thank you so much for the suggestion and help from @KnathanM. Just a random thought, since molecule featurizers were included as x_d right? Can we or should we also include the atom and bond featurizers in the datapoint as V_d and E_f respectively?
