### ISSUE TITLE
[v2 BUG]: Binary-mcc not working as a --loss-function and --metrics

### ISSUE THREAD

**Issue by ddgunizar** [chemprop/chemprop#940]
**Describe the bug**
When using Binary-mcc as a --loss-function or --metrics there is an internal error.

**Example(s)**
```
chemprop train --data-path Full_database_reaction.csv --task-type classification --output-dir full_database_reaction_yield_suzuki --split-type scaffold_balanced --reaction-columns smiles --rxn-mode reac_diff_balance --ignore-columns yield --metrics binary-mcc

chemprop train --data-path Full_database_reaction.csv --task-type classification --output-dir full_database_reaction_yield_suzuki --split-type scaffold_balanced --reaction-columns smiles --rxn-mode reac_diff_balance --ignore-columns yield --loss-function binary-mcc
```

**Expected behavior**
I expect to obtain the mcc value in Entire test set results but I obtain an error. The same in the case of using it as a --loss-function.

**Error Stack Trace**

**Error for --metrics binary-mcc:**

```
File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Scripts\chemprop.exe\__main__.py", line 7, in <module>
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\cli\main.py", line 80, in main
    func(args)
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\cli\train.py", line 75, in func
    main(args)
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\cli\train.py", line 995, in main
    train_model(
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\cli\train.py", line 854, in train_model
    trainer.fit(model, train_loader, val_loader)
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\lightning\pytorch\trainer\trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\lightning\pytorch\trainer\call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\lightning\pytorch\trainer\trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\lightning\pytorch\trainer\trainer.py", line 986, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1028, in _run_stage
    self._run_sanity_check()
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1057, in _run_sanity_check
    val_loop.run()
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\lightning\pytorch\loops\utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\lightning\pytorch\loops\evaluation_loop.py", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\lightning\pytorch\loops\evaluation_loop.py", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\lightning\pytorch\trainer\call.py", line 311, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\lightning\pytorch\strategies\strategy.py", line 411, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\models\model.py", line 157, in validation_step
    losses = self._evaluate_batch(batch)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\models\model.py", line 182, in _evaluate_batch
    return [
           ^
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\models\model.py", line 183, in <listcomp>
    metric(preds, targets, mask, None, lt_mask, gt_mask) for metric in self.metrics[:-1]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\nn\metrics.py", line 66, in forward
    return self._calc_unreduced_loss(preds, targets, mask, lt_mask, gt_mask)[mask].mean()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\nn\loss.py", line 208, in _calc_unreduced_loss
    TP = (targets * preds * weights * mask).sum(0, keepdim=True)
          ~~~~~~~~~~~~~~~~^~~~~~~~~
TypeError: unsupported operand type(s) for *: 'Tensor' and 'NoneType'
```

**Error for --loss-function binary-mcc:**

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Scripts\chemprop.exe\__main__.py", line 7, in <module>
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\cli\main.py", line 80, in main
    func(args)
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\cli\train.py", line 75, in func
    main(args)
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\cli\train.py", line 995, in main
    train_model(
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\cli\train.py", line 822, in train_model
    model = build_model(args, train_loader.dataset, output_transform, input_transforms)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\cli\train.py", line 746, in build_model
    criterion = Factory.build(
                ^^^^^^^^^^^^^^
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\utils\registry.py", line 46, in build
    return clz_T(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D.Dalmau\anaconda3\envs\robert\Lib\site-packages\chemprop\nn\loss.py", line 39, in __init__
    task_weights = torch.as_tensor(task_weights, dtype=torch.float).view(1, -1)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: must be real number, not NoneType
```

**Screenshots**

**Environment**
- Python 3.11.4
- package versions: chemprop 2.0.2
- Windows

**Checklist**
- [ ] all dependencies are satisifed: `conda list` or `pip list` shows the packages listed in the `pyproject.toml`
- [ ] the unit tests are working: `pytest -v` reports no errors

**Additional context**

**Comment by JacksonBurns** [comment]
Thanks for the report @ddgunizar, I've edited your comment to add code formatting.

@KnathanM could you take a look at this?

**Comment by ddgunizar** [comment]
Thanks, @shihchengli! I tried to use your code, and it seems that the program is working fine with the --metrics binary-mcc, but no value is obtained for the test set. This line no longer appears: Entire Test Set results: {'entire_test/roc': 0.5630034804344177, 'entire_test/prc': 0.8161526918411255, 'entire_test/accuracy': 0.6930692791938782, 'entire_test/f1': 0.800000011920929, 'entire_test/bce': 0.5536601614243913}

**Comment by shihchengli** [comment]
I can see the entire test results on my side. If you mean the results for different metrics, currently it would only use the default metrics if the `--metrics` flag is not used, or only use what you provide in `--metrics`. In your case, you can try adding `--metrics binary-mcc prc accuracy f1 bce` to your prompts.

**Comment by ddgunizar** [comment]
![Screenshot 2024-06-28 150235](https://github.com/chemprop/chemprop/assets/107545954/526ca46e-da93-4f56-8b5b-0d9b92f0e57e)

**Comment by ddgunizar** [comment]
Is this normal, or did I inadvertently use a command line option to hide it, and now I can't see it?  @shihchengli

**Comment by shihchengli** [comment]
<img width="1017" alt="Screen Shot 2024-07-02 at 10 50 05 AM" src="https://github.com/chemprop/chemprop/assets/63532555/0859cbbc-e0a3-44c7-a294-2191d624fced">
Above are the results I ran below command line :

```
python ~/chemprop/chemprop/cli/train.py \
-i ~/chemprop/tests/data/regression/mol/mol.csv \
--epochs 1 \
--task-type regression \
--output-dir train_example \
--devices 1
```

The default is DEBUG if you run the Python script directly. If you use `chemprop train` instead, you need to use `--verbose` to print out the information. By default, it is set to `logging.ERROR`. You can increase the verbosity level by specifying the flag multiple times. The levels after `logging.ERROR` are `logging.WARNING`, `logging.INFO`, and `logging.DEBUG`. To get the predicted metrics output, use `--verbose` twice in your command line.

**Comment by shihchengli** [comment]
@ddgunizar I have opened a PR in #953 to change the default verbose level to INFO. You can add `-vvv` in the command line to resolve this issue in your current version.

**Comment by ddgunizar** [comment]
@shihchengli, thank you for all the information; it was really helpful!
