### ISSUE TITLE
[v2 BUG]: `TypeError` when manually specifying `--loss-function` as its default

### ISSUE THREAD

**Issue by JacksonBurns** [chemprop/chemprop#966]
**Describe the bug**
When specifying `--loss-function mse` via the CLI, a `TypeError` is raised.

**Example(s)**
This code works:
```bash
chemprop train --output-dir chemprop_fromp \
	--data-path monomer_stability_and_heat_released.csv \
	--smiles-columns monomer \
	--target-columns G_DA_200 H_RO_200 \
	--task-type regression \
	--metrics mae mse rmse r2 \
	--batch-size 32 \
	--show-individual-scores
```
but this does not:
```bash
chemprop train --output-dir chemprop_fromp \
	--data-path monomer_stability_and_heat_released.csv \
	--smiles-columns monomer \
	--target-columns G_DA_200 H_RO_200 \
	--task-type regression \
	--loss-function mse \  # <---- manually specifying the default loss function
	--metrics mae mse rmse r2 \
	--batch-size 32 \
	--show-individual-scores
```

**Expected behavior**
Explicitly passing the default should work the same as leaving Chemprop to determine the default.

**Error Stack Trace**
```
(chemprop_v2_live) jackson@jackson-Precision-7540:~/fastprop_fromp$ . chemprop.sh 
Wrote config file to chemprop_fromp/config.toml
Traceback (most recent call last):
  File "/home/jackson/miniconda3/envs/chemprop_v2_live/bin/chemprop", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jackson/miniconda3/envs/chemprop_v2_live/lib/python3.11/site-packages/chemprop/cli/main.py", line 80, in main
    func(args)
  File "/home/jackson/miniconda3/envs/chemprop_v2_live/lib/python3.11/site-packages/chemprop/cli/train.py", line 74, in func
    main(args)
  File "/home/jackson/miniconda3/envs/chemprop_v2_live/lib/python3.11/site-packages/chemprop/cli/train.py", line 1007, in main
    train_model(
  File "/home/jackson/miniconda3/envs/chemprop_v2_live/lib/python3.11/site-packages/chemprop/cli/train.py", line 820, in train_model
    model = build_model(args, train_loader.dataset, output_transform, input_transforms)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jackson/miniconda3/envs/chemprop_v2_live/lib/python3.11/site-packages/chemprop/cli/train.py", line 744, in build_model
    criterion = Factory.build(
                ^^^^^^^^^^^^^^
  File "/home/jackson/miniconda3/envs/chemprop_v2_live/lib/python3.11/site-packages/chemprop/utils/registry.py", line 46, in build
    return clz_T(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jackson/miniconda3/envs/chemprop_v2_live/lib/python3.11/site-packages/chemprop/nn/loss.py", line 39, in __init__
    task_weights = torch.as_tensor(task_weights, dtype=torch.float).view(1, -1)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: must be real number, not NoneType
```

**Screenshots**
N/A

**Environment**
- python version 3.11.9
- package versions: `conda list` or `pip list`
```
# packages in environment at /home/jackson/miniconda3/envs/chemprop_v2_live:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aimsim-core               2.2.1                    pypi_0    pypi
aiohttp                   3.9.5                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
astartes                  1.2.2                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
chemprop                  2.0.3                    pypi_0    pypi
configargparse            1.7                      pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
idna                      3.7                      pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
lightning                 2.3.3                    pypi_0    pypi
lightning-utilities       0.11.5                   pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
mhfp                      1.9.6                    pypi_0    pypi
mordredcommunity          2.0.6                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi
multiprocess              0.70.16                  pypi_0    pypi
ncurses                   6.5                  h59595ed_0    conda-forge
networkx                  3.3                      pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.5.82                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
openssl                   3.3.1                h4bc722e_2    conda-forge
packaging                 24.1                     pypi_0    pypi
padelpy                   0.1.16                   pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.0               pyhd8ed1ab_0    conda-forge
psutil                    6.0.0                    pypi_0    pypi
python                    3.11.9          hb806964_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch-lightning         2.3.3                    pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
rdkit                     2024.3.3                 pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
scikit-learn              1.5.1                    pypi_0    pypi
scipy                     1.14.0                   pypi_0    pypi
setuptools                71.0.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
sympy                     1.13.1                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
torch                     2.3.1                    pypi_0    pypi
torchmetrics              1.4.0.post0              pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
triton                    2.3.1                    pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yarl                      1.9.4                    pypi_0    pypi
```
- OS
Ubuntu 22.04

**Checklist**
- [x] all dependencies are satisifed: `conda list` or `pip list` shows the packages listed in the `pyproject.toml`
- [ ] the unit tests are working: `pytest -v` reports no errors

Didn't this check, but I just installed from PyPI and I have no local changes.

**Additional context**
You can download the dataset I am running this on if you want to reproduce the exact error locally from this Zenodo: https://zenodo.org/records/10892219

**Comment by JacksonBurns** [comment]
That looks like it should work. Once we release 2.0.4, let's link that PR to this issue and have it automatically close. Leaving this up until then so that people know it is fixed on `main`.

**Comment by JacksonBurns** [comment]
This has since been resolved.
