### ISSUE TITLE
Issue with  split_type scaffold_balanced

### ISSUE THREAD

**Issue by matany58** [chemprop/chemprop#98]
Each time I used split_type scaffold_balanced as shown below I received error
python train.py --data_path data/tox21.csv --dataset_type classification --split_type scaffold_balanced --save_dir tox21_checkpoints

Traceback (most recent call last):
  File "train.py", line 7, in <module>
    chemprop_train()
  File "/research/sharedresources/leadDiscoveryInformaticsCenter/projects/ML/conda_envs/chemprop/chemprop/train/cross_validate.py", line 154, in chemprop_train
    cross_validate(args=TrainArgs().parse_args(), train_func=run_training)
  File "/research/sharedresources/leadDiscoveryInformaticsCenter/projects/ML/conda_envs/chemprop/chemprop/utils.py", line 383, in wrap
    result = func(*args, **kwargs)
  File "/research/sharedresources/leadDiscoveryInformaticsCenter/projects/ML/conda_envs/chemprop/chemprop/train/cross_validate.py", line 86, in cross_validate
    model_scores = train_func(args, data, logger)
  File "/research/sharedresources/leadDiscoveryInformaticsCenter/projects/ML/conda_envs/chemprop/chemprop/train/run_training.py", line 61, in run_training
    train_data, val_data, test_data = split_data(data=data, split_type=args.split_type, sizes=args.split_sizes, seed=args.seed, num_folds=args.num_folds, args=args, logger=logger)
  File "/research/sharedresources/leadDiscoveryInformaticsCenter/projects/ML/conda_envs/chemprop/chemprop/data/utils.py", line 399, in split_data
    return scaffold_split(data, sizes=sizes, balanced=True, seed=seed, logger=logger)
  File "/research/sharedresources/leadDiscoveryInformaticsCenter/projects/ML/conda_envs/chemprop/chemprop/data/scaffold.py", line 76, in scaffold_split
    scaffold_to_indices = scaffold_to_smiles(data.mols(), use_indices=True)
  File "/research/sharedresources/leadDiscoveryInformaticsCenter/projects/ML/conda_envs/chemprop/chemprop/data/scaffold.py", line 41, in scaffold_to_smiles
    scaffold = generate_scaffold(mol)
  File "/research/sharedresources/leadDiscoveryInformaticsCenter/projects/ML/conda_envs/chemprop/chemprop/data/scaffold.py", line 24, in generate_scaffold
    scaffold = MurckoScaffold.MurckoScaffoldSmiles(mol=mol, includeChirality=include_chirality)
  File "/home/manyanwu/.conda/envs/chemprop/lib/python3.7/site-packages/rdkit/Chem/Scaffolds/MurckoScaffold.py", line 109, in MurckoScaffoldSmiles
    scaffold = GetScaffoldForMol(mol)
  File "/home/manyanwu/.conda/envs/chemprop/lib/python3.7/site-packages/rdkit/Chem/Scaffolds/MurckoScaffold.py", line 73, in GetScaffoldForMol
    res = Chem.MurckoDecompose(mol)
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdmolops.MurckoDecompose(list)
did not match C++ signature:
    MurckoDecompose(RDKit::ROMol mol)

**Comment by swansonk14** [comment]
Hi @matany58, thanks for bringing up the issue! This was due to a recent change that we unfortunately didn't test carefully. It has now been fixed in this commit: https://github.com/chemprop/chemprop/commit/2c98bf743cf90893dcc7b9f2b70786a2c7735b2f. Please let me know if you run into any more issues.

**Comment by matany58** [comment]
Please have this being updated in the githup/chemprop site.

Thanks,

Matthew

**Comment by swansonk14** [comment]
Yes the master branch has been updated with these changes, so if you pull master again you should get the fix.
